### ISSUE TITLE
Tooltips don't seem to work on vega

### ISSUE THREAD

**Issue by metasoarous** [metasoarous/oz#1]
I checked the vega implementation, and it works (all in all), but the tooltips don't seem to be working. Will have to figure out how they're supposed to install differently for vega vs vega-lite.

**Comment by maacl** [comment]
Should I exclude vega and vega tooltip from oz if I include separate new
versions?

**Comment by metasoarous** [comment]
You can exclude, yes. But IIRC, as long as you put whatever of the vega/vega-lite/vega-tooltip libs you're using above oz in your dependencies list, those versions will take precedent over whatever oz is specifying as a dependency.

**Comment by maacl** [comment]
Thanks.

**Comment by bombaywalla** [comment]
I don't know if it's related to this issue, but I've been bitten by [this similar vega issue](https://github.com/vega/vega-tooltip/issues/120) when using oz. According to that issue history, it's been addressed by Vega 4. I looked at cljsjs, but the latest there seems to be Vega 3.3.1-1.

If you've been able to get oz to use Vega 4, would you please show me how.
Thanks.

**Comment by metasoarous** [comment]
Hi @bombaywalla - I've been working on a script for building updates to the various `cljsjs/vega*` libs, which you can find here: https://github.com/metasoarous/oz/blob/master/bin/update-cljsjs.sh. There's also some notes in the README now down at the bottom about how to override the default versions: https://github.com/metasoarous/oz#debugging--updating-vegavega-lite-versions. Hopefully I be a able to mint a release soon that addresses all of these issues, but if not, feel free to try running the `update-cljsjs.sh` script yourself, as it should install the cljsjs libs to your local maven repository.

**Comment by bombaywalla** [comment]
Thanks.

**Comment by MnRA** [comment]
So I'm guessing this is still something that hasn't been added and I can ignore the `vegaTooltip.vega is not a function` error I'm getting? 
(after much investigation I found out vegaTooltip used to have a 'vega' function until 0.9.0, from the time of writing it's around version 0.17.0)

**Comment by metasoarous** [comment]
Hi @MnRA. Thanks for reminding me about this.

This has not been resolved yet, unfortunately. I've been holding off because I've been thinking more generally about passing in customizations to the way you run embed (see #59 for example). Feel free to submit a specific pull request for this particular issue though. Otherwise, I'll get to it when I'm able, and make sure to report back on this issue.

Thanks again!

**Comment by MnRA** [comment]
Oh no pressure, If I end up needing it for my project (or I stumble upon a nice solution) I'll make a pull request. Still learning the Oz and Vega, So it's probably going to be a while before I can.

Thanks for your work.

**Comment by gklijs** [comment]
I don't get the issue, but maybe I'm thinking of a different tooltip? I used oz for https://open-bank.gklijs.tech/average-kb-cpu.html source at https://github.com/gklijs/open-bank-mark/tree/data-ch-languages-one-broker tooltips work fine. When hovering over a line you see all the info for that point.

**Comment by diegovdc** [comment]
I am getting an error on the browser console `vegaTooltip.vegaLite is not a function` (https://quihubolecontupandemia.netlify.com/). However there is also a tooltip there and it shows the correct info.
Rendering is done with `reagent` and compiling with `shadow-clj`. 

Source: https://github.com/diegovdc/covid-spread

**Comment by metasoarous** [comment]
I think this is no longer an issue. Thanks for chiming in folks!

**Comment by metasoarous** [comment]
Went ahead and verified that this is no longer an issue by adding a tooltip to one of the vega examples (see f317e7b), and indeed it works fine, without any extraneous error messages. Thanks again folks!

**Comment by maacl** [comment]
Great, thanks.
