### ISSUE TITLE
How much interest in making this a consumer-facing lib?

### ISSUE THREAD

**Issue by sooheon** [metasoarous/oz#10]
Thanks for the excellent library!

It looks like a great dev time / internal tool. What are the steps necessary to make this something that can drive visualizations inside webapps (competing with something like [recharts](http://recharts.org)), and what is your level of interest in that direction?

**Comment by metasoarous** [comment]
This is already something you can do using the oz reagent components in `oz.core`: `vega`, `vega-lite` and `view`. If there is anything that doesn't feel consumer-ready about the results, please raise a specific issue.
