### ISSUE TITLE
Support WSL environments?

### ISSUE THREAD

**Issue by hindol** [metasoarous/oz#104]
Currently, running `oz/start-server!` in a Windows WSL environment produces the following error,

```
Error:
Execution error (IOException) at java.lang.ProcessImpl/forkAndExec (ProcessImpl.java:-2).
error=2, No such file or directory
```

This is because oz relies on `xdg-open` I believe. See: #70

Is there a known workaround for this?

**Comment by metasoarous** [comment]
Hi @Hindol! Thanks for asking. I'd love to be able to support WSL environments if possible. I don't know what the equivalent of `xdf-open` would be for that environment, but I'm happy to accept a pull request if you sort it out. Please let me know if I can be of help getting a dev environment set up for you. Thanks again!

**Comment by Hindol** [comment]
Hi @metasoarous. How do you feel about skipping the `xdg-open` entirely? Starting up a server bound to a port should work seamlessly.

**Comment by metasoarous** [comment]
Hi @hindol. Thanks again for raising this issue.

As of a release a few weeks ago (see commits 6c15e85 & 3f391f1) failed calls to `xdg-open` are caught and a message is printed telling you what address to visit.

If someone figures out how, I'd happily accept a PR which opens the link for Windows/WSL systems, but I wouldn't know how to do this, and am not sure if it's even possible. If you don't know how either but would like to see it happen, please feel free to submit a separate issue for tracking. For now, Oz should work fine with WSL.

Thanks again!

**Comment by hindol** [comment]
Hi @metasoarous, Thanks for getting back on this.

Last time I checked, there were no clear alternatives to `xdg-open` under WSL. There are a few third party scripts that can do this, but that needs additional setup. I think the way you have done it right now works the best.

**Comment by metasoarous** [comment]
@hindol OK; Thanks for the feedback! Please feel free to bring it up if you find that anything changes there.

Thanks again!
