### ISSUE TITLE
TypeError: vegaTooltip.vegaLite is not a function in browser console

### ISSUE THREAD

**Issue by lucywang000** [metasoarous/oz#107]
Version: built from current master

**Comment by metasoarous** [comment]
Hi @lucywang000. Thanks for reporting!

This will be fixed soon.

**Comment by metasoarous** [comment]
Hi @lucywang000. I believe this should be fixed now. Please give `1.6.0-alpha8` a whirl, and let me know if this resolves the issue. Thanks again!

**Comment by metasoarous** [comment]
Doing some issue cleanup, and closing this now, since I haven't heard any further reports of this.

Long story short is that we were using an outdated form of the API incompatible with the newer `vega*` versions. This has been fixed now.

Thanks again for reporting!
