### ISSUE TITLE
Server workflow possible?

### ISSUE THREAD

**Issue by judepayne** [metasoarous/oz#108]
Hi,
I am already using this terrific library clojurescript-side with shadow-cljs. My page has many visualisations and is getting a bit slow. 
I am just wondering how to go about turning the production of each new day's set of images (my underlying data only updates daily) into a server side process that would output a series of image files (e.g. svg's) to a folder somewhere. This would make my client side page a lot simpler and do all the heavy lifting of data preparation and vega-lite visualisation just once.
Any tips on how to get started?
Thanks!

**Comment by metasoarous** [comment]
Hi @judepayne!

Thanks for asking about this.

Please see #36. This feature is inbound. It's actually already implemented via the `vega-cli` npm module in a private function, but I'm in the process of sorting out the API for this as it relates to the `html` output function, and the (en. route) general purpose `compile` and `export!` functions.

Bear with me please; My hope is to have _something_ to release, even if its a bit rough, later this week.

Thanks again!

**Comment by judepayne** [comment]
Awesome! Look forward to it :)

**Comment by metasoarous** [comment]
Also, so you're aware, I think the default behavior of exporting hiccup with visualizations will be to embed a static image which "comes alive" when the data loads.

**Comment by metasoarous** [comment]
Hi @judepayne; Please see my most recent comment on #36 regarding testing out the new `vega-cli` function. It's still a work in progress, and the api may change slightly, but I'd love to have folks kicking the tires. Thanks!

**Comment by judepayne** [comment]
Hi @metasoarous I will try to have a kick of the tyres later on today. thanks!

**Comment by judepayne** [comment]
Hi, will reply on #36
