### ISSUE TITLE
use vg-cli function from library vg-cli

### ISSUE THREAD

**Issue by behrica** [metasoarous/oz#109]
I extracted the vg-cli function "as is" to an extra library, so it can be re-used outside Oz
https://github.com/metasoarous/oz/blob/d02be35e82396f006e205a16656419b77f364184/src/clj/oz/core.clj#L322

It propose to use it in Oz.

I will make a PR

**Comment by metasoarous** [comment]
Hi @behrica 

Thanks again for submitting this!

Again, as mentioned in #111, I'm settling on an API that looks a little different here. Sorry for taking so long to get around to this, but I'm going to make a point of releasing something (even if just another alpha) this week.

Thanks again!

**Comment by metasoarous** [comment]
Hi @behrica. Thanks again for submitting this.

The above changes have been out for a bit so I'm going to close this issue now. I may decide to release some more stripped down libraries that match the API I've settled on if there's sufficient demand, so please feel free to provide additional feedback or open up another issue.

Thanks again!
