### ISSUE TITLE
Generating pure static websites with no overhead

### ISSUE THREAD

**Issue by pavel-klavik** [metasoarous/oz#113]
Is it possible to set build to generate a static website with no overhead, mathjax included, the default styles? I would like to just pass the full hiccup starting with [:html ...] and get it as the entire website (plus probably some JS injected to allow hot code reloading).

**Comment by metasoarous** [comment]
Yes! It is now (in part). Please take a look at the `1.6.0-alpha7-SNAPSHOT` release (or if you're on `deps.edn`, the latest master version). There's some debugging to do here, to be sure, as a lot of the underlying mechanics have changed, and docstrings need to be updated. But you should be able to poke around the code base to find the `:omit-XXX` options for leaving out styles, libs, etc. It's a WIP, so please let me know if you have any trouble. I'm trying to clean this work up this week. Thanks!

**Comment by lambda-ai** [comment]
Hi, i see you added a flag to omit mathjax, but then removed it. I need to support a website where there is no internet access, so I need to serve all the dependencies, but the mathjax one is problematic. So I guess my question is why  you removed the flag to omit mathjax. Thanks!

**Comment by lambda-ai** [comment]
actually it doesnt matter: i can just provide a hiccup data structure with a top [:html] and provide my own header, so no problems.

**Comment by metasoarous** [comment]
Closing this now, as between @lambda-ai's suggestion and https://github.com/metasoarous/toto, this is now eminently possible.
