### ISSUE TITLE
Does oz support arc-pie?

### ISSUE THREAD

**Issue by xavierchow** [metasoarous/oz#118]
I got a blank web page when applying [arc-pie](https://vega.github.io/editor/#/examples/vega-lite/arc_pie) to oz,

```clj
(def arc-pie
  {:data     {:values [{:tag "foo" :total-num 5} {:tag "bar" :total-num 3}] }
   :mark     "arc"
   :encoding {:theta {:field "total-num" :type "quantitative"}
              :color {:field "tag" :type "nominal"}}
   :view     {:stroke nil}
   })

(oz/view! arc-pie)
```

Checking the web console, I got the following errors,
```
oz.js:141 TypeError: Cannot read property 'orient' of undefined
    at ci (oz.js:28)
    at hp (oz.js:28)
    at new wp (oz.js:28)
    at jp (oz.js:28)
    at Object.e.compile (oz.js:28)
    at CB (oz.js:1205)
    at Object.<anonymous> (oz.js:1206)
    at Object.componentWillUpdate (oz.js:822)
    at updateClassInstance (oz.js:206)
    at beginWork (oz.js:215)
Ud @ oz.js:141
oz.js:253 Uncaught TypeError: Cannot read property 'orient' of undefined
    at ci (oz.js:28)
    at hp (oz.js:28)
    at new wp (oz.js:28)
    at jp (oz.js:28)
    at Object.e.compile (oz.js:28)
    at CB (oz.js:1205)
    at Object.<anonymous> (oz.js:1206)
    at Object.componentWillUpdate (oz.js:822)
    at updateClassInstance (oz.js:206)
    at beginWork (oz.js:215)
```

I'm not sure it's a defect or oz doesn't support arc at all, any idea?

**Comment by metasoarous** [comment]
Hi @xavierchow. Thanks for the report.

Can you please tell me which version you're using? Thanks.

**Comment by xavierchow** [comment]
@metasoarous thanks for the quick response, I'm using `1.6.0-alpha6`

**Comment by charignon** [comment]
I have the same issue and can report that `(json/generate-string pie-plot)` in my case generates a correct pie plot that I can render in the vega lite online editor but it does not view through oz with the same stacktrace.

**Comment by charignon** [comment]
This is fixed for me in `1.6.0-alpha7-SNAPSHOT`

**Comment by metasoarous** [comment]
Thanks for the report @charignon! That SNAPSHOT has some further fixes/updates as well, FWIW. Will release a non-SNAPSHOT versions soon.

**Comment by metasoarous** [comment]
Update: Please now see `1.6.0-alpha8`. Thanks!

**Comment by metasoarous** [comment]
Hi @xavierchow. I'm going to go ahead and close this issue now, but please let me know if it remains unsolved for you in the latest release `1.6.0-alpha12`. Thanks!
