### ISSUE TITLE
Better document transform, especially calculate

### ISSUE THREAD

**Issue by LEHunter** [metasoarous/oz#119]
Excuse me if this is a dumb question, but I can't find it in the documentation and none of the examples seem to use it.  

How is one supposed to use vega-lite's :transform and :caulculate operators in Oz?  I've tried passing in strings that vega-lite understands and using more Clojure native kinds of calculations, but nothing seems to work.  

Pointers to documentation or examples would be great.  The actual thing I am trying to do is translate dates in the form of integers YYYYMMDD into something vega-lite recognizes as a date.

**Comment by metasoarous** [comment]
Hi @LEHunter. Thanks for asking about this, and sorry for taking a while to get back to you.

You should be able to pass in the exact same strings as used in regular old json vega/vega-lite specs. I'd love to build (or accept a PR with) a compiler step that translates some minimal clojure-esque subset to the vega/vega-lite expression JS-subset, but it's low on my list of priorities at the moment :-)

With that, I'll refer you to the official vega-lite/vega docs. The only thing I can add to them that is sometimes you have kebab-case keywords in your clojure data, and so in these cases you have to use `"data['clj-keyword-name']" to access these attributes from your expressions. Both fortunately and unfortunately, the example datasets don't exhibit this pattern frequently, and so examples of expressions like this are a little short to come by. But once you know the trick, it's pretty easy to adapt. 

Please let me know if this solves your problem, and feel free to submit a README.md PR if you'd like to help make this clearer for others.

Thanks again!

**Comment by metasoarous** [comment]
Hi @LEHunter.

Thanks again for bringing this to my attention. I've updated the README to point out this potential gotcha.

After thinking about it a bit, it may actually not be _too_ hard to come up with a thing that would translate basic sexprs into Vega-Lite expressions, so I'll open up a new issue for this. For now, I'm closing this particular issue, but please let me know if there are additional points of clarification which should be added about how to use Vega-Lite/Vega from Oz & Clojure more generally. In general, I don't want to reinvent the wheel when the IDL folks have put together such thorough documentation, but I'm happy to smooth out any rough spots with translation.

Thanks again
