### ISSUE TITLE
Unknown repeated value "layer" warning

### ISSUE THREAD

**Issue by jgoodhcg** [metasoarous/oz#123]
I'm trying to render a multi layered graph using `:repeat`, in a similar way to [this example](https://vega.github.io/vega-lite/docs/datum.html#using-datum-to-color-multi-series-chart).

```clojure
(def macro-line-plot
  {:data   {:values data}
   :repeat {:layer ["prot" "fat" "carbs"]}
   :spec   {:mark     "line"
            :encoding {:x     {:field "date" :type "temporal"}
                       :y     {:field {:repeat "layer" } :type "quantitative"}
                       :color {:datum {:repeat "layer" :type "nominal"}}}}})
```

Using `oz/view!` to render this displays a flat line with js/console warning `Unkown repeated value "layer"`.

If I open the graph in the vega-editor then it displays correctly.

**Comment by jgoodhcg** [comment]
After some more searching it looks like this is related to [another issue](https://github.com/metasoarous/oz/issues/117) and probably a result of vega-lite version mismatch?

**Comment by metasoarous** [comment]
Thanks for the report.

Yeah, makes sense to me that it could be a version issue. Two things to try:
* compile the spec to json and plug into the online editor
* try out the `1.7.0-alpha7-SNAPSHOT` version, which has more recent vega libs

Thanks again

**Comment by jgoodhcg** [comment]
@metasoarous I think you had a typo in your version , but `1.6.0-alpha7-SNAPSHOT` worked.

**Comment by metasoarous** [comment]
Perfect! Thanks!
