### ISSUE TITLE
A typo at dev/user.clj line 64 of contour-plot

### ISSUE THREAD

**Issue by yubrshen** [metasoarous/oz#126]
For the line of 
`(def contour-plot (json/parse-string (slurp "resources/oz/examples/contour-lines.vega.json")))`
should be 
`(def contour-plot (json/parse-string (slurp "resources/oz/examples/vega/contour-lines.vega.json")))`
inserting 'vega' subdirectory.
I tested the fix, and confirmed it working. 
I can submit a pull to fix, but it might be easier to fix by you.

**Comment by metasoarous** [comment]
Hi @yubrshen. Thanks for reporting this! I'll try to get around to fixing that this week, but probably not till Tuesday or Wednesday. In the mean time, please feel free to submit a PR if you'd like to be listed as a contributor :-)

Thanks again!

**Comment by yubrshen** [comment]
> Hi @yubrshen. Thanks for reporting this! I'll try to get around to fixing that this week, but probably not till Tuesday or Wednesday. In the mean time, please feel free to submit a PR if you'd like to be listed as a contributor :-)
> 
> Thanks again!

Thanks for giving me the opportunity to participate! I've created  a PR with indication of issue #126.

**Comment by metasoarous** [comment]
Thanks again for submitting that PR @yubrshen! Closing this issue now.
