### ISSUE TITLE
oz.core/vega-lite returns nil?

### ISSUE THREAD

**Issue by lucasemmoreira** [metasoarous/oz#138]
Hi there, very nice lib!
I had this code, a while a go and I tried to run it again but an error came up.

Here is the code
```
[oz/vega-lite {:layer [{:data {:values [{:time 1 :weight 1 :curve "None"}]}
                              :encoding {:x {:field "time" :type "quantitative"}
                                         :y {:field "weight" :type "quantitative"}
                                         :color {:field "curve" :type "nominal"}}
                              :mark "point"}]}]
```

Here is the error

```
template.cljs:353 Uncaught Error: Assert failed: Invalid Hiccup form: [nil {:layer [{:data {:values [{:time 1, :weight 1, :curve "None"}]}, :encoding {:x {:field "time", :type "quantitative"}, :y {:field "weight", :type "quantitative"}, :color {:field "curve", :type "nominal"}}, :mark "point"}]}]
```

As far as I can tell, it seems that oz.core/vega-lite is returning nil and hiccup complains. Did the behaviour of vega-lite changed?

**Comment by metasoarous** [comment]
Hi @lucasemmoreira.

Thanks for the kind words, and for submitting this issue :-)

It looks like you're using the Reagent library, yes? I'm not sure why the `oz/vega-lite` var would be getting nuked and set to nil. It sounds like this _did_ work the first time and then stopped? Can you tell me anything more about this transitioning from working to not working? Also, is this code up anywhere that I could take a look at it?

Thanks again!

**Comment by lucasemmoreira** [comment]
@metasoarous Thank you for the fast answer!
Indeed, I am using reagent library. Unfortunatly, I think that I have little information about the transitioning. One thing that I know, it is that it has been so long that I formatted my computer between the test that work and the one it didn't.
Another bad news is that the code that I have this problem is work related, so I do not feel very comfortable publishing open.
I guess I will close this thread for now, and if can reproduce this error again on a open project I will open again.

**Comment by metasoarous** [comment]
Hi again @lucasemmoreira.

I do want to try to help you here if I can, so I'm going to reopen.

Can you please tell me a little more about your setup? What version of Oz are you using? Are you using Leiningen or `deps.edn`? How about figwheel/`cljsbuild` or 'shadow-cljs`? We've seen some issues recently with using the latest with figwheel  & `cljsbuild` (see #137), which is maybe related. However, I can say that I just recently put the Reagent API through the ringer visualizing election data (see: http://2020-election-results.surge.sh), and it worked perfectly fine via `shadow-cljs`.

Please let me know if you have any more information that might help here.

Thanks!

**Comment by lucasemmoreira** [comment]
Hello @metasoarous ! I appreciate your time for helping me. Sorry it took me so long to answer.
Lets go! I will try to answer all your questions.
The version of oz I am using is [metasoarous/oz "1.6.0-alpha34"].
I am using Leiningen with shadow-cljs.
I have no ideas of what more information to offer for now.

**Comment by metasoarous** [comment]
Hi @lucasemmoreira.

Thanks for the update.

This is pretty strange. I was almost sure that this had to be an issue with `cljsbuild` since it worked fine in `shadow-cljs` for me. But if you're using shadow as well, then I'm a bit clueless. It's _possible_ there's some issue with Leiningen + shadow, but I sort of doubt it.

Would you please try reproducing in a minimal example as you suggested to see where things go awry?

Thanks again!

**Comment by lucasemmoreira** [comment]
I am having some trouble to reproduce the problem. It is very strange because it is not working only in a single project of mine... While I don't reproduce a minimal code with the error, I may have gotten a new clue.
When I loaded the project today I got this error on the oz loading. I have installed vega, vega-lite and vega-embed. (I have probably missed this message before. My apologies)
![image](https://user-images.githubusercontent.com/22220766/100866668-c4a78e80-3477-11eb-93b4-4ccbf9cc49bd.png)
It looks like I may be missing something?

**Comment by lucasemmoreira** [comment]
@metasoarous it was some old mistake (not sure what exactly) I have made on the build of the project.
To solve, I ensured that vega was installed, removed the .shadow-cljs/ and the output-dir, then I recompiled and worked!
Thank you for the attention!
