### ISSUE TITLE
Using oz as a reagent lib shouldn't activate sente machinery

### ISSUE THREAD

**Issue by maacl** [metasoarous/oz#14]
I am getting a lot of taoensso.sente errors in the console using 
```
[:div
 [oz.core/vega { ... }]
 [oz.core/vega-lite { ... }]]
```
in reagent components. Is the graph server really needed?

**Comment by metasoarous** [comment]
@maacl Thanks for bringing this up.

It's very clear what the issue is here; The `oz.core` namespace (https://github.com/metasoarous/oz/blob/master/src/cljs/oz/core.cljs) starts the sente server, which it really shouldn't if `oz.core` is to be used as the Reagent API namespace. The solution here is probably to pull out all of the sente crap and put it in another namespace, maybe `oz.app`, and make that the main namespace of compilation target so that when running things from the repl, `oz.app` runs, but when `oz.core` is required as a lib, this does not happen.

@maacl Are things otherwise working, aside from the errors?

**Comment by maacl** [comment]
Yes, quite beautifully thank you.

For now I will just spawn a server to get rid of the messages.

**Comment by maacl** [comment]
Adding the below to my server.clj still retains the sente errors in the browser console.
```
(defn -main [& args]
  (let [port (Integer/parseInt (or (env :port) "3000"))]
 ->   (oz/start-plot-server!)
    (run-jetty handler {:port port :join? false})))
```

**Comment by maacl** [comment]
Any news on this or hints as to how I can prevent the errors? I would like to help if feasible.

**Comment by metasoarous** [comment]
I haven't had time to work on this yet, but if you're keen to help I'd very much appreciate it!

In short, all of the stuff in the `core.cljs` function having to do with Sente and the plot server should be moved into an `app.cljs`. All that's left in `core` then should be the basic Reagent functionality, suitable for a lib, which then gets required by the `app` namespace. The `app` namespace is what will then get compiled to a target served up by the plot server, leaving the Reagent lib code free of cruft. Does that seem reasonable to you?

**Comment by maacl** [comment]
I think something else is broken too.

If I clone your version of the project I get the following error in the
browser when running the instructions from the readme.

12socket.js:97 WebSocket connection to
'ws://localhost:3449/figwheel-ws/dev' failed: Error in connection
establishment: net::ERR_CONNECTION_REFUSED

**Comment by metasoarous** [comment]
Hmm... OK. I'll try to take a look at this soon.

**Comment by awb99** [comment]
I am trying to use this library to do some vega lite charting in reagent also. So far my attempts failed. But I am a clojure beginner.  :(. It would be really nice to have an example that one could copy and paste to get going with vega lite as reagent component quickly. I had a look at many clojure libraries... And to me it seems this one is pretty much the only vega lite wrapper that had been made public.

**Comment by metasoarous** [comment]
@maacl I just released `[metasoarous/oz "1.4.0-SNAPSHOT"]`, which should solve this issue. Please give it a whirl and tell me how it goes. If all looks good, I'll mint an non-SNAPSHOT release.

**Comment by maacl** [comment]
Big improvement. I am getting a few errors related to tooltips, but I think that is result of me mixing up vega versions for a custom vega pie chart. Thanks a lot.

**Comment by metasoarous** [comment]
@maacl I've finally released `1.4.0`, with this fix and a bunch of additional goodies. Please let me know how it goes if you get a chance to update.

**Comment by maacl** [comment]
@metasoarous Thanks, will do. Focused on other aspects of the app right now, so might be a little while.

**Comment by metasoarous** [comment]
No problem; Thanks
