### ISSUE TITLE
Error from darkstar when trying to package project into uberjar

### ISSUE THREAD

**Issue by jimmyhmiller** [metasoarous/oz#145]
When trying to package my project with [uberdeps](https://github.com/tonsky/uberdeps) I get a conflict with graal js and regex.

Packaging you see the error as follows.

```clojure
.   metasoarous/darkstar 0.1.0
.     org.graalvm.js/js 20.0.0
.       com.ibm.icu/icu4j 64.2
.       org.graalvm.regex/regex 20.0.0
! Duplicate entry "META-INF/services/com.oracle.truffle.api.TruffleLanguage$Provider" from "org.graalvm.regex/regex 20.0.0" already seen in "org.graalvm.js/js 20.0.0"
.       org.graalvm.sdk/graal-sdk 20.0.0
.       org.graalvm.truffle/truffle-api 20.0.0
! Duplicate entry "META-INF/versions/11/module-info.class" from "org.graalvm.truffle/truffle-api 20.0.0" already seen in "org.graalvm.js/js 20.0.0"
.       org.ow2.asm/asm 7.1
.       org.ow2.asm/asm-analysis 7.1
.       org.ow2.asm/asm-commons 7.1
.       org.ow2.asm/asm-tree 7.1
.       org.ow2.asm/asm-util 7.1
.     org.graalvm.js/js-scriptengine 20.0.0
```

This ends up resulting in a runtime error as follows.

```clojure
SyntaxError: No language for id regex found. Supported languages are: [js]
```

I can make a project for you with a reproducible test case. But just wanted to start off with a report of the problem.

**Comment by jimmyhmiller** [comment]
Here is some information where some other project dealt with this problem. https://github.com/reactiverse/es4x/issues/57

**Comment by jimmyhmiller** [comment]
So this appears to be an uberdeps issue. Depstar seems to handle it fine. Sorry if this is the wrong place to report. Feel free to close if you want and I can make a post over there.

**Comment by metasoarous** [comment]
Hi @jimmyhmiller. Thanks for the report.

I think ultimately this is a uberdeps issue, so you'll want to report there. But I do appreciate you posting here as well so that others may find this in the future (if it takes a while for uberdeps to fix the problem).

Thanks again!
