### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by joefromct** [metasoarous/oz#152]
Hi and thank you for OZ.

I noticed a broken link in the readme: 

The first hyperlink underneath the section [requiring-in-clojupyter](https://github.com/metasoarous/oz/blob/master/README.md#requiring-in-clojupyter).

Broken link points to:  https://github.com/metasoarous/oz/tree/master/examples/clojupyter-example.ipynb

**Comment by metasoarous** [comment]
Closed by #156; Thanks for bringing this to our attention @joefromct!
