### ISSUE TITLE
How to export the spec to png?

### ISSUE THREAD

**Issue by tadas-subonis** [metasoarous/oz#163]
I don't think that there is an example of how to do that.

**Comment by metasoarous** [comment]
As with the other example you posted about, you can simply do `(oz/export! plot "outfile.png")` or manually specify `:to-format :png` if you need to.

**Comment by metasoarous** [comment]
I'm starting a wiki space so folks can more easily contribute examples along these lines.

https://github.com/metasoarous/oz/wiki/Usage-Examples

Please feel free to add other examples if you feel it would be helpful for others.

Thanks again!
