### ISSUE TITLE
Clarify how to get started

### ISSUE THREAD

**Issue by holyjak** [metasoarous/oz#17]
When I create a simple project and run `(oz/v! line-plot)` in the REPL, it fails with 

```
ERROR [oz.core:34] - error sending plot to server: nil
```

while I expect it to open a browser window with the plot. What did I do wrong? Perhaps I need to manually access some URL first?

Thank you!

**Comment by holyjak** [comment]
Yes. Sorry :)

**Comment by metasoarous** [comment]
No problem; Thanks for clarifying. Feel free to chime in on #18 if you like.

**Comment by holyjak** [comment]
Thank you that you care! :-)
