### ISSUE TITLE
Fix oz 1.6.0-alpha35 not working in leiningen

### ISSUE THREAD

**Issue by metasoarous** [metasoarous/oz#170]
As @mn-dimension reported here: https://github.com/metasoarous/oz/issues/168#issuecomment-937709328

> I am getting the following error.
>
>     eval (current-form): (require '[oz.core :as oz])
>     (err) Syntax error compiling at (clojure/tools/reader/edn.clj:75:9).
>     (err) No such var: err/throw-no-dispatch
>
> To replicate:
>
>     lein new test-oz
>
> add the dependency so that the project is
>
>     (defproject test-oz "0.1.0-SNAPSHOT"
>       :description "FIXME: write description"
>       :url "http://example.com/FIXME"
>       :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
>                 :url "https://www.eclipse.org/legal/epl-2.0/"}
>       :dependencies [[org.clojure/clojure "1.10.3"]
>                      [metasoarous/oz "1.6.0-alpha35"]]
>       :repl-options {:init-ns test-oz.core})
>     lein repl
>     (require '[oz.core :as oz])

After trying these versions of Clojure and oz out in the `clj` tooling, I was not able to reproduce this error. This has me thinking that this is a result of differences in the way clj tooling and lein resolve dependencies.

My suggestion for solving this issue (aside from moving to `clj`, which I've been much happier with), is to have a detailed look at the output of `lein deps :tree` and `clj -X:deps tree` to see what's getting resolved differently (you [may have to](https://stackoverflow.com/a/33100334/177677) do `lein pom && mvn dependency:tree -Dverbose=true` to get the _complete_ tree out of lein, if this ends up being another AOT compilation issue). 

I have a hunch that the issue may be in `taoensso/encore`, since attempting to require `oz.core` a second time gives this:

```
test-oz.core=> (require '[oz.core :as oz])
Syntax error compiling at (taoensso/encore.cljc:1:1).
namespace 'clojure.tools.reader.edn' not found
```

However, it could be _another_ library is AOT compiled against this version, which is causing the issues in encore. If I had to wager a hunch, I'd look at `clojupyter`, since it tends to be behind a lot of these issues. But looking through the deps as described above should lead to the error.

**Comment by metasoarous** [comment]
I don't have time to look at this in greater depth right now @mn-dimension, but can try to get around to it next week. Please feel free to investigate further yourself if you're able, and I can cut a new release for you if you sort out what versions need to get updated here (though it may be that a third party lib needs to update _their_ dependencies).

Thanks in advance!

**Comment by mn-dimension** [comment]
Thanks. I will give it a go and let you know.

I'm not sure either but I do know the dependency tree created by lein and clj/deps.edn are created differently. 
Lein is order dependent in the project file and clj/deps.edn takes the "latest" version. 
I think it will be something to do with this.

At some point I will move over from lein. tp clj tools :)

**Comment by mn-dimension** [comment]
FYI - lein works with `2.0.0-alpha5` - never got to the bottom of why the other version failed !

**Comment by JovanToroman** [comment]
For me it was the `tools.reader` dep. when moving to a newer Datomic version. I updated it to the latest v. and the problem disappeared.
