### ISSUE TITLE
Call start-plot-server automatically on v!

### ISSUE THREAD

**Issue by metasoarous** [metasoarous/oz#18]
Was thinking about #17, and am thinking maybe calling `v!` should run `start-plot-server` automatically if its not already running?

**Comment by holyjak** [comment]
If it is easy to do then the user convenience that it provides would be nice, I think. If it adds extra complexity to the code then it perhaps is not worth it?

**Comment by metasoarous** [comment]
This is now implemented in `1.4.0`. Sente doesn't have a good mechanism for delaying the sending of the first message till connection is established, and so to be safe, I just have it wait 7.5 seconds when it first starts up the server before sending any messages over the wire. Additionally, when the page loads it will now say "first plot may take a while to load" so users aren't too confused.

@holyjak If you get a chance to try it out, please let me know how it goes.
