### ISSUE TITLE
Oz does not seem to respect the xOffset setting

### ISSUE THREAD

**Issue by athos** [metasoarous/oz#182]
I'm porting [this Vega-Lite example code](https://vega.github.io/vega-lite/docs/encoding.html#example-grouped-bar-chart) to Oz. When I tried it with Oz like this:

```clojure
(require '[oz.core :as oz])

(oz/view! {:data {:values
                  [{:category "A" :group "x" :value 0.1}
                   {:category "A" :group "y" :value 0.6}
                   {:category "A" :group "z" :value 0.9}
                   {:category "B" :group "x" :value 0.7}
                   {:category "B" :group "y" :value 0.2}
                   {:category "B" :group "z" :value 1.1}
                   {:category "C" :group "x" :value 0.6}
                   {:category "C" :group "y" :value 0.1}
                   {:category "C" :group "z" :value 0.2}]}
           :mark "bar"
           :encoding
           {:x {:field "category"}
            :y {:field "value" :type "quantitative"}
            :xOffset {:field "group"}
            :color {:field "group"}}})
```

I saw the following result rendered, which doesn't seem to respect the [`xOffset`](https://vega.github.io/vega-lite/docs/encoding.html#positon-offset) setting:

<img width="156" alt="Screen Shot 2021-12-20 at 22 37 31" src="https://user-images.githubusercontent.com/27441/146775577-4bb0f358-99fd-4dad-988f-c271976ede17.png">

Do you have any idea on what is going on?

**Comment by metasoarous** [comment]
Hi @athos. Thanks for reporting.

I'm assuming this is just a bug with some specific vega library.

If you want to test this out, you could follow the instructions in the README on the latest vega-lite & vega versions: 

https://github.com/metasoarous/oz#debugging--updating-vegavega-lite-versions

Last time I tried to update, there may have been an issue with the latest vega-embed, so maybe don't update that one until I've had a chance to sort it out.

I'll try to cut a release with updated versions soon.

Thanks again

**Comment by athos** [comment]
@metasoarous Thank you for the quick response!

> I'll try to cut a release with updated versions soon.

I'm looking forward to it!

**Comment by metasoarous** [comment]
Hello again @athos. I just released `2.0.0-alpha5` with the latest vega library versions. Please give that a shot and let me know if it fixes this issue. Thanks!

**Comment by athos** [comment]
@metasoarous Hi, thanks! I've confirmed `2.0.0-alpha5` fixes the issue 👍

![visualization](https://user-images.githubusercontent.com/27441/147079116-6fdfeccc-4570-4b14-8213-06416a1c0b0b.png)

**Comment by metasoarous** [comment]
Excellent; Thanks for reporting back!
