### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gigasquid** [metasoarous/oz#30]
I didn't see a license file in the project. We are considering using it in Apache (incubating) MXNet.
Could you please clarify?

**Comment by gigasquid** [comment]
I see it in the project file - this right? Eclipse? https://github.com/metasoarous/oz/blob/master/project.clj#L6

**Comment by gigasquid** [comment]
I think EPL is fine, but I'll let you know if there are any problems. Here is the issue so you can track it :)
https://github.com/apache/incubator-mxnet/issues/13701

**Comment by awb99** [comment]
@metasoarous Thank you so much for this library! I know it is just a small library, but I think a very important one: Today most data-science is still done on Python, but I believe that Clojure is way better for data-science than Python. And really what is missing is quick & easy visualizations. And this is what you provide!

**Comment by metasoarous** [comment]
@awb99 Thanks so much! Glad you like it. Can't agree with you more. Between data-viz and ML projects with Clojure bindings like MXNet, Clojure is growing into some real potential as a data-science tool. Excited to see this area grow in the next couple years!

**Comment by awb99** [comment]
What I am still searching for is some more samples of cool vega/lite
examples.  I have already many use cases for which I could not find
samples.

**Comment by metasoarous** [comment]
@awb99 Have you taken a look at https://vega.github.io/vega-lite/examples/ and/or https://vega.github.io/vega/examples/? They're pretty extensive in the kinds of vizualizations and behavior represented. I've generally found that anything I want to do is more or less a stitching together a couple of examples and tweaking a few details. If there's something specific you want to do but can't find an example of, the Vega/Vega-Lite team is pretty open to suggestions for demonstrations.

**Comment by metasoarous** [comment]
Closed by 9003f89.
