### ISSUE TITLE
Static export options

### ISSUE THREAD

**Issue by metasoarous** [metasoarous/oz#36]
Leftover from #5: Right now we have live-embed html output support via `export!` but would like to add support for `svg` output, from which we should be able to tackle `jpg` or `png`, as well as `pdf` (or even just `html` without the need for js).

**Comment by behrica** [comment]
Yes, SVG export woule be nice. This would help to avoid the work arround I described in the org mode use case #42.
I use vega lite to have static SVG charts in my org mode reports.

**Comment by BorisVSchmid** [comment]
Export to file would be great! Using oz for generating the figures for my publications, and it is nice to avoid the manual step of selecting "save as" from the figures.

**Comment by gklijs** [comment]
Seems like commit ce44634bafe6d0f5d5bc2816dcdb08c467381460 made things worse. I got it set up to generate multiple .html files, which can then be put on Netlify. But adding the compiled cljs broke this. I'm not sure why this is needed, I guess it's some preparations to load it dynamically from a reagent component. Because of this I can't update from 1.6.0-alpha2, when it did work easily. I might however change it slightly for my purposes. As the data is already going into a separate json.

**Comment by realgenekim** [comment]
@metasoarous Congrats on the Clojurists Together grant, and great seeing you (very) briefly at the Conj a couple of months ago!

If all goes well, I'm going to take a stab at this today — I will try both approaches you describe in #5.  

Approach #1:  Use the npm executables `vl2svg` and`vg2svg`.

Approach #2: Create something like `view!` that returns SVG result, so that it be transformed into PNG without any external dependencies.  (Planisphere used jBrowserDriver, which uses JavaFX, which isn't available in some post-Java8 distributions. Is there a maven package that you'd recommend instead, which doesn't require specific JDK?  Do you think HtmlUnit is suitable?)

- https://github.com/HtmlUnit/htmlunit
- https://github.com/robert-spurrier/planisphere

PS: my use case:  I'm generating 30 graphs that I want to use as frames of animation.  I want to generate PNG files so that I can use ImageMagick, as described [here]( https://imagemagick.org/discourse-server/viewtopic.php?t=24912).

Thanks!  Gene

**Comment by realgenekim** [comment]
Just a status report:  I have successfully created a looping GIF as described above!  With almost no changes to oz, I was able to generate all the PNG frames using the (currently) private function `oz.core/vg-cli`.

@metasoarous, I propose the following function in `oz.core` — if you agree, I'll submit a PR, and some instructions on how to use it to create animated GIF.  (And it will include corrected error handling when vl2png/etc.executable is not found.)

```
(defn export-png
  [spec filename]
  (#'oz/vg-cli
    {:spec spec
     :format :png
     :return-output? false
     :output-filename filename}))
```

PS: here's the looping GIF!  :)
![loop](https://user-images.githubusercontent.com/2114462/75369476-5a264a00-5878-11ea-96f3-a05ceaaa1bdd.gif)

**Comment by behrica** [comment]
There are other clojure libraries who need some from of vega-> something (svg, html. hiccup) transformation.
Maybe this could become a tiny, single purpose library.

https://github.com/scicloj/notespace/issues/6

**Comment by behrica** [comment]
> There are other clojure libraries who need some form of vega-> something (svg, html. hiccup) transformation.
> Maybe this could become a tiny, single purpose library.
> 
> [scicloj/notespace#6](https://github.com/scicloj/notespace/issues/6)

I started such a package here: https://github.com/behrica/vg-cli

It is currently the exact code from oz/vg-cli
https://github.com/metasoarous/oz/blob/d02be35e82396f006e205a16656419b77f364184/src/clj/oz/core.clj#L322

I will do a first release very soon,
and then 'oz' could be changed to use it from there.

And it will be re-used in "notespace" as well.

https://github.com/scicloj/notespace/pull/8

**Comment by behrica** [comment]
I just deployed https://clojars.org/vg-cli/versions/0.0.1.

I will do a PR to oz to use it

**Comment by metasoarous** [comment]
Hi @realgenekim & @behrica!

Thank you both for your comments! And my apologies for not getting back sooner. I've been deep in hammock & spec mode on this particular issue and have some commits inbound soon.

For now, I would like for Oz to maintain its own `vega-cli` API. The API is going to be a little different than what you saw on master and have forked over, and for the sake of consistency, I would like for this API (the opts spec in particular) to be as consistent as possible with the more general purpose `compile` api which is coming up (feel free to take a look at my most recent blog posts: http://metasoarous.com/blog; there's a lot of subtlety here in how hiccup vs vega should get compiled, separately, together, etc).

Second point here: I _may_ have a clever idea for how to get compilation to work _without_ having to deal with installing the `vega-cli` via npm, which is really my preferred route forward here if I can help it. So my hope is that the `vega-cli` will really just be a backup solution.

Obviously, all of this code is open source, and you're free to do what you like with it. However, if you do want to maintain a fork of that particular code, I'd suggest waiting till Oz's `vega-cli`/`compile` aPI is finalized. Overall, it benefits everyone for our APIs to be (eventually) consistent.

Thanks again!

**Comment by metasoarous** [comment]
Also @realgenekim: Awesome animation! Loved seeing that SO MUCH! I totally want to make that an easier thing to do!

**Comment by metasoarous** [comment]
I just pushed up to master a working draft of the `vega-cli` api, and some of the `compile` api implementation. If you're using `deps.edn`, you can refer to the current git hash (or master) as a version tag if you'd like to kick the tires. More on the way soon! Thanks!

**Comment by judepayne** [comment]
Hi @metasoarous, I tested out the `vega-cli` function.
I made a new clj project - deps.edn - and pulled in by the latest SHA.
I had an error with one of your dependencies when requiring oz.core:

    Syntax error (FileNotFoundException) compiling at (oz/core.clj:1:1).
    Could not locate respeced/test__init.class, respeced/test.clj or respeced/test.cljc on classpath.

I didn't waste to much time trying to figure that out and why a call in `clj` in terminal wasn't pulling down that dependency. I just added it manually to my `deps.edn`, ran `clj` again and it got pulled down this time, then deleted that entry. Might be worth looking into.

The function itself seems to work great. I only tested `:vega-lite` stuff though.
Some minor comments:
- initially I didn't npm install the vega & vega-lite dependencies that this wraps. I didn't get a very useful error, but I notice in your comment, you'll fix that with a throw.
- The args to the function could maybe be simplified. There's overlap between mode and from and vega-doc and input-filename. That's a personal style thing though. Personally I would not have input and output filenames and let the user of your library slurp and spit.

This is great. Thanks so much!
How will the `compile` api take this further?

**Comment by daslu** [comment]
For reference, just putting here a link to a discussion going on these days about different ways to render vega to image:
https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/rendering.20charts.20in.20notespace/near/192911226

**Comment by judepayne** [comment]
Thanks for the zulip link.

For veg-cli you can avoid the use of files to stage input, by using the `:in` key for `clojure.java.shell/sh`. Zac  Tellman's rhizome library has some examples. https://github.com/ztellman/rhizome/blob/master/src/rhizome/viz.clj

**Comment by metasoarous** [comment]
@daslu Thanks for pointing that out! I'll make sure to post there when I get things working.

@judepayne Yeah, an earlier implementation used `:in` and `:out`, but `:out` doesn't work with png/pdf where you want byte arrays, so I switched wholesale. Could probably go back to using `:in` though.

**Comment by judepayne** [comment]
hi @metasoarous 

How about something like this?

    (defn vega-cli
      "Takes doc and uses the vega/vega-lite cli tools as specified by mode to translate to the specified format. output-filename is optional.
       This var is semi-public; It's under consideration for fully public inclusion, but consider it alpha for now."
      ([{:keys [vega-doc mode to output-filename] ;; TODO may add seed and scale eventually
         :or {to :svg from :vega-lite}}]
       {:pre [(#{:vega-lite :vega} mode)
              (#{:png :pdf :svg :vega} to)]}
       (if (vega-cli-installed? mode)
         (let [short-mode (case (keyword mode) :vega-lite "vl" :vega "vg")
               ext (name (if (= to :vega) :vg to))
               command (str short-mode 2 ext)
               js (json/encode vega-doc)
               {:keys [out err]}
               (cond
                 (#{:pdf :png} to) (shell/sh command :in js :out-enc :bytes)
                 :else (shell/sh command :in js))]
           (if (empty? err)
             (cond
               output-filename   (if (bytes? out)
                                   (bytes->file output-filename out)
                                   (spit output-filename out))
               :else out)
             (throw (RuntimeException. err))))
         (throw (RuntimeException. "Vega CLI not installed! Please run `npm install -g vega vega-lite vega-cli` and try again. (Note: You may have to run with `sudo` depending on your npm setup.)")))))


too much time on my hands with the quarantine! That seems to work in terms of returning the svg/vega as strings or png/pdfs as a byte array to the repl - i.e. no files & simplifies the interface to the function a bit. I left in output-filename so that users didn't have to write their own bytes->file function.

In case, it affects anyone else, I encountered this error when trying to run any of the `vl2png` `vl2pdf` `vg2png` or `vg2pdf` tools:

    TypeError: Cannot read property 'getContext' of null

but found a fix for that [here](https://github.com/vega/vega/issues/666)

**Comment by metasoarous** [comment]
Thank you all so much for contributing to this issue.

At long last, with some debugging help from @admiralbumblebee in #140, I'm happy to report that Oz now supports static output of png and svg via both the` vega-cli` (installable from `npm`) and svg via [darkstar](https://github.com/applied-science/darkstar) (using graal to run vega from the JVM!). There may still be dragons here, so please do feel free to raise issues if you hit any speedbumps (in particular, some of the defaults around when to use which routine may need improving). But I believe we're now at a point where I can close this issue. This one has been a long time in coming!

Do note that I may be pulling in `darkstar` directly into this codebase in order to maintain version consistency (see #141).

Again, thank you all so much!
