### ISSUE TITLE
clickable links opening in new tabs.

### ISSUE THREAD

**Issue by BorisVSchmid** [metasoarous/oz#40]
I am looking to make clickable links in a vega visualisation (href) in oz to open in new tabs. One of the issues listed on vega's github offers a solution (adding some bit of syntax to the loader), but I am at a bit of a loss how to use this in oz.

https://github.com/vega/vega/issues/1171

```
new vega.View(runtimeSpec, {
  loader: vega.loader({target: '_blank'})
});
```

**Comment by metasoarous** [comment]
Hey @BorisVSchmid. Thanks for reporting!

Do you think this is a sane default for folks to expect? If so I'm not opposed to the idea.

There's currently no way to pass through view opts to `vega.View` from `Oz`, but this would be a nice feature to have, solving both this issue and setting the course for #13 and similar functionality.

**Comment by BorisVSchmid** [comment]
Even though I would want it to open in new tabs, I think it is best to follow vega's default here - links don't open new tabs by default. Keeps oz mirroring vega.

But I agree it would be a nice feature to have somewhere in the future - either through a change in vega, or through a hack in oz.

**Comment by metasoarous** [comment]
Hey @BorisVSchmid! This should now be possible, at least if you're using the Reagent API (building an app). You can pass through view options to the Reagent component. This is _also_ possible via the REPL api, but only really works if the options map you're passing in is pure data (I'm guessing `vega.loader()` returns an object).

I'm going to close this for now, but please feel free to reopen or start a new issue if you'd like to make a case for supporting this from the REPL api.

Thanks again!
