### ISSUE TITLE
allow for selecting the svg renderer in interactive mode?

### ISSUE THREAD

**Issue by BorisVSchmid** [metasoarous/oz#43]
It looks like the default renderer of oz is "canvas", but if I want to put text on the screen that can be copy-pasted, I need the svg renderer. Is it possible to have the renderer option also be available in v!. Right now it looks like I can only pass the mode option (vega or vega-lite~) to v!

**Comment by metasoarous** [comment]
Doing some issue cleanup; The `opts` argument of `view!` and friends now get passed through to the call to `vegaEmbed`, so you can pass `:renderer :svg` to accomplish this. You can also specify `:static-embed :svg` for static svg rendering of visualizations in md/html documents.

Thanks again for bringing this up @BorisVSchmid!
