### ISSUE TITLE
Conflicting public/index.html found in classpath

### ISSUE THREAD

**Issue by viesti** [metasoarous/oz#44]
I ran into an odd issue when trying out oz with the [Clojure CLI](https://clojure.org/guides/deps_and_cli). The server seems to start fine:

```
0% cat deps.edn
{:deps {metasoarous/oz {:mvn/version "1.5.2"}}}
0% clj
Clojure 1.10.0
user=> (require '[oz.core :as oz])
nil
user=> (oz/start-plot-server!)
19-02-01 20:48:25 xxx INFO [oz.server:113] - Web server is running at `http://localhost:10666/`
nil
```

But when a browser window opens, there's an error in the Javascript console:

<img width="1175" alt="js-error" src="https://user-images.githubusercontent.com/57011/52149348-0d703f80-2675-11e9-9459-b9b658c2c3a7.png">

The above works with Leiningen though.

**Comment by metasoarous** [comment]
Hi @viesti. Thanks for reporting!

This issue is rather strange... It's not clear to me where the `example.core` ns is coming from. Can you please post more of the stacktrace there? Do you have any code in this repo aside from `deps.edn`?

Thanks again

**Comment by viesti** [comment]
So dabbled a bit further, might be a difference in how [tools.deps.alpha](https://github.com/clojure/tools.deps.alpha) resolves the classpath:

cli:
```
0% clj
Clojure 1.10.0
user=> (require '[clojure.java.io :as io])
nil
user=> (io/resource "public/index.html")
#object[java.net.URL 0x37ddb69a "jar:file:/Users/kimmoko/.m2/repository/markdown-to-hiccup/markdown-to-hiccup/0.6.1/markdown-to-hiccup-0.6.1.jar!/public/index.html"]
```

lein
```
0% lein repl
nREPL server started on port 57002 on host 127.0.0.1 - nrepl://127.0.0.1:57002
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.10.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_191-b12
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[clojure.java.io :as io])
nil
user=> (io/resource "public/index.html")
#object[java.net.URL 0x3569b91f "jar:file:/Users/kimmoko/.m2/repository/metasoarous/oz/1.5.2/oz-1.5.2.jar!/public/index.html"]
```
So with the cli, a different index.html get's resolved 😱

**Comment by metasoarous** [comment]
Woah! Bizzaro.

Seems then like this should be reported as bug in one of `tools.deps.alpha` or Clojure CLI?

Thanks again

PS Random aside; I see you live in Espoo. Do you by happenstance know Timo Erkkilä?

**Comment by viesti** [comment]
Happened to have a quick chat at #tools-deps, Dominic there pointed out that since there is a resource with same name in the classpath, one could use a namespaced prefix for the oz resource.

Re: Random Aside. Sorry, doesn't ring a bell immediately, among the Timos I know :)

**Comment by viesti** [comment]
Actually, looking at contents of markdown-to-hiccup-0.6.1.jar, it might contain unnecessary artifacts (a dev time cljs compiler output). Still, if Oz is used as a dependency in a project, there will be a conflict with `public/index.html`, if the said project also has a resource with this name in it's classpath.

So maybe it would be best to have a unique name for this index resource, or generate it via code in the ring handler, to avoid name clashes on the classpath.

**Comment by metasoarous** [comment]
This should be fixed now. Thanks @viesti!

**Comment by viesti** [comment]
Glad to help :)
