### ISSUE TITLE
Error in IClojure notebook

### ISSUE THREAD

**Issue by tothda** [metasoarous/oz#46]
I'm running IClojure on OSX Mojave in the official docker container, with the command: `docker run -p 8888:8888 cgrand/iclojure`.

I got the following error when trying to require `oz.notebook.iclojure` namespace:

```
Exception while doing something unexpected.
#unrepl/browsable
  [#error
     {:via [{:type clojure.lang.Compiler$CompilerException,
             :message
               "Syntax error compiling deftype* at (flatland/ordered/set.clj:12:1).",
             :data {:clojure.error/phase :compile-syntax-check,
                    :clojure.error/line 12, :clojure.error/column 1,
                    :clojure.error/source "flatland/ordered/set.clj",
                    :clojure.error/symbol deftype*},
             :at [clojure.lang.Compiler analyzeSeq "Compiler.java" 7114]}
            {:type java.lang.IllegalArgumentException,
             :message "Must hint overloaded method: toArray",
             :at [clojure.lang.Compiler$NewInstanceMethod
                  parse "Compiler.java" 8496]}],
      :trace [[clojure.lang.Compiler$NewInstanceMethod
               parse "Compiler.java" 8496]
              [clojure.lang.Compiler$NewInstanceExpr build "Compiler.java" 8058]
              [clojure.lang.Compiler$NewInstanceExpr$DeftypeParser
               parse "Compiler.java" 7934]
              [clojure.lang.Compiler analyzeSeq "Compiler.java" 7106]
              [clojure.lang.Compiler analyze "Compiler.java" 6789]
              [clojure.lang.Compiler analyze "Compiler.java" 6745]
              [clojure.lang.Compiler$BodyExpr$Parser parse "Compiler.java" 6118]
              [clojure.lang.Compiler$LetExpr$Parser parse /8] /9],
      /10}
   /11]
```

![image](https://user-images.githubusercontent.com/7077/52377986-b698aa80-2a66-11e9-969d-54e76367b482.png)

This is the output of the docker container:

[iclojure.log](https://github.com/metasoarous/oz/files/2838520/iclojure.log)

**Comment by metasoarous** [comment]
Hi @tothda. Thanks for reporting. Can you please try 1.5.0? I'm curious to see if 1.5.3 broke something.

**Comment by metasoarous** [comment]
I'm reproducing this error in 1.5.0 now. I never myself tested out this cause I was never able to get the IClojure working in my Linux environment (hence the impetus behind HCADatalab/IClojure#7, but that came after I released 1.5.0). The person who tested out 1.5.0 for me was @keesterbrugge.

Can you please give us any more information about your environment that might help us solve this @keesterbrugge?

Thanks in advance

**Comment by keesterbrugge** [comment]
1.5.5 loads outside of docker without problem

![screenshot 2019-02-07 at 19 23 05](https://user-images.githubusercontent.com/6086439/52433705-f4044300-2b0d-11e9-84d8-1d20d1857fa4.png)

Inside a docker container I get the same error.

**Comment by metasoarous** [comment]
Thanks for testing this out @keesterbrugge! Would you please get us version information for python, jupyter, Clojure and IClojure? I have a feeling we're going to have to raise an IClojure issue.

**Comment by metasoarous** [comment]
Actually, this looks to be related to this issue: clj-commons/ordered#40 (via owainlewis/yaml#28; see PR owainlewis/yaml#32). I've updated the version of `org.flatland/ordered` to 1.5.7 (see e02199c), and this seems to resolve the issue. Hopefully we get an update to `io.forward/yaml` with this new version soon, but until then I have this working in `metasoarous/oz "1.5.6-SNAPSHOT"`, and will push up a non-snapshot release momentarily.

Thanks to everyone who pitched in on reporting and debugging this issue!
