### ISSUE TITLE
exported document gives vega-lite error

### ISSUE THREAD

**Issue by nickstares** [metasoarous/oz#48]
When I `export!` a document, the resulting html file does not display the `vega-lite` elements and gives the following error in the console: 
```
Uncaught SyntaxError: Unexpected end of input  vega-lite@3.0.0-rc11:1 
```
I can reproduce this with:
```clojure
(oz/export! [:div [:h1 "foo"]] "foo.html")
```
Maybe there is an issue with the `vega-lite` CDN? Looks like the most recent version is `rc12`.

**Comment by metasoarous** [comment]
Hi @nickstares. Thanks for reporting.

Did you try manually editing the html to see if incrementing to `rc12` does the trick? I've put out `[metasoarous/oz "1.5.7-SNAPSHOT"]`, which exports html that requires this more up to date vega-lite. Please let me know if that solves the problem for you.

Thanks

**Comment by nickstares** [comment]
Hi @metasoarous ,

I just tested it again with `1.5.6` and I didn't encounter the error -- `rc11` loads fine. Not sure what the original problem was, but glad it's resolved! Thanks for your help here.

**Comment by metasoarous** [comment]
LOL; Great. All's well that ends well.

Computers, right? :man_shrugging:
