### ISSUE TITLE
More robust export and static rendering

### ISSUE THREAD

**Issue by metasoarous** [metasoarous/oz#5]
Would be nice to be able to save views as svg and png files, and for the composite views, as html or perhaps with https://github.com/clj-pdf/clj-pdf thrown in the mix, to pdf. Could imagine a grammar around the pdfs that could render nicely as html. Maybe useful for static sites / blogs as well? Embedding in md? Latex? Let's get crazy!

**Comment by realgenekim** [comment]
Yes, totally!  I would love to be able to generate SVG and PNG files in a batch mode, as opposed to an interactive REPL session.

I just ran into the Planisphere that was also forked from Vizard: https://github.com/robert-spurrier/planisphere

It apparently uses jBrowserDriver to drive vega/vega-lite.

My use case: I'm doing a bunch of analyses in a batch mode, driven from a Makefile.  I'd love to just output an HTML file, along with the generated SVG/PNG graphics files.  SPSS was super great at things like that.  :)

Let me know what kind of help you're looking for!  I'm motivated, because I have an urgent need for it.  (What relevant skills I can bring is a totally different story. :)

**Comment by metasoarous** [comment]
Amazing! Yes please! I'd love help with this.

There are two paths I have foreseen us taking here. The easiest is to just call out to the `vl2png`, `vl2svg`, `vg2png` & `vg2svg` executables packaged with the `vega` and `vega-lite` npm packages. While easy to implement, this requires folks to install those modules, which maybe isn't too much to ask for the feature, but would still be nice to avoid.

It's heartening to see that this was accomplished in planisphere using a headless browser. The way it handles this is that the `send-spec` function always returns the `svg` of the compiled viz, so the only tweak for headless compilation is to pass `:headless true` to this function when you don't have a real browser connected (and this in fact becomes the default). This can then be manually translated to `jpg` via the `svg->jpeg` function. This seems like a fairly sane pattern, but it does come with the cost of always having to send the compiled svg over the wire back to the REPL during interactive usage, which may not always be desirable. It also comes with additional complexity for us because it raises the question of how to handle the hiccup parts of the spec. For these reasons, I think things would be simpler if there was a separate function for this.

Here's my working suggestion: a `compile` fn with arguments `:to-file`, `:viz-format` and `:view-format`:
* `:viz-format` would let you decide between `:svg`, whatever formats we can easily convert to (`:png`, `:jpg`, etc), and something like `:live`, which would embed the js code required to boot up the vega visualizations in the context of a `:view-format :html` compilation (which would be the default for hiccup specs, and the same as the `:viz-format` for single specs, but would let you additionally specify `:pdf` for `pdf` output). 
* `:to-file` would act orthogonal to this, letting us write any kind of compilation to a file as necessary (this would be required probably for any `:viz-format` other than `:svg` or `:live`, such as `:png` and `:jpg`), and via extensions could also be used to inform the defaults `:viz-format` value as appropriate.

Thoughts on that approach?

**Comment by metasoarous** [comment]
I'm closing this for now and opening a second issue for static svg, jpg & pdf now that we have live-embed html output support. Thanks!
