### ISSUE TITLE
(oz/v!) of boxplot of 60K elements takes over 10m to render

### ISSUE THREAD

**Issue by realgenekim** [metasoarous/oz#54]
Hi, @metasoarous — 

As you know, I absolutely love oz.  :)  But for months, I've had to resort to using incanter to generate boxplots, because it required over 10m between the moment I called `(oz/v!)` and the graph being rendered in the browser.

I've always assumed that this was a limitation in vega-lite, but on a whim, I finally copied the JSON into the vega-lite editor.  And it rendered in milliseconds!  So the problem is in oz, not in vega-lite.  (I'm kicking myself for not trying this earlier.)

Enclosed is the screenshot of the vega-lite editor, and you can find the EDN file that generates the long render time here:  

https://gist.githubusercontent.com/realgenekim/cfd961575d3f171c5b8f5b0fbd5a3ce0/raw/301b30a2094c14bec7118a68ed09a21e11d2f234/ozout.edn

Any thoughts on how to speed up the render?   THANK YOU!

<img width="1107" alt="vega_editor" src="https://user-images.githubusercontent.com/2114462/53711288-52170400-3df6-11e9-8f26-07ec79417c33.png">

PS: I'm starting to look at the oz source to better understand how it works, because I still want to try generating static PNG or SVG files.  But I suspect you could more quickly diagnose what is causing the long render times.  :)

**Comment by metasoarous** [comment]
Hi @realgenekim. Thanks for reporting!

I have been wrestling with some significant lag in getting data to screen as well. In my case, it's not even including a viz, just some tables and stuff based on data! And as you yourself have discovered, it's not the render time itself that is making things take long (vega rendering is actually relatively fast). My suspicion is that it's either the time it takes to send the data over the socket, one of the pre-processing functions, or something in the way it's plugging into the react/reagent machinery that is making it take so long. I'd love to have help sorting this out if you have any cycles to put some clues together.

Again, would love to see progress on the static rendering side of things, as there's a lot that it unlocks (see #52 & #org). Please note though that discussion of that issue has moved from #5 (which was closed to recognize that basic "live-embed" html output has been completed), to #36, which represents the more truly "static" export side of the story.

Thanks again for your enthusiasm and efforts.

**Comment by realgenekim** [comment]
Thanks for the info — super helpful.  I started looking at the source code last night, and I'll get a local build of it going later today.  

1.  Can you send me the EDN of the data that you send `oz/v!` is slow to render?  It's interesting that the data doesn't have to be large...

2.  Can you confirm that the `taoensso.timbre` logging output for ClojureScript goes to the browser console?  I've never seen any of those logging messages ever, and am wondering if I'm looking in the right place.

Will keep you posted!

**Comment by realgenekim** [comment]
Confirmed that updated `vega-embed` does indeed fix the performance issues. Performance now matches running in the vega-lite online editor.  Many thanks!  This is awesome!
