### ISSUE TITLE
Bad CSRF Token ? 

### ISSUE THREAD

**Issue by jdkealy** [metasoarous/oz#55]
Hi, 

I'm trying out this library and after I launch the plot-server, the network inspector has " Bad CSRF token" as a response in the /chsk websocket route. I'm using an app that has reagent-template with ring defaults and such. Could that be what's causing this? Anyway to pass options to the plot server to have it disable CSRF tokens ?

**Comment by jdkealy** [comment]
Ah... I had a conflicting version of sente. Amazing library thanks.

**Comment by metasoarous** [comment]
Happy your problem is resolved. Thanks for reporting.

Glad the library is proving useful for you :-)
