### ISSUE TITLE
'markdown-to-hiccup.core' not found

### ISSUE THREAD

**Issue by NikolaF94** [metasoarous/oz#56]
Keep getting this exception:
CompilerException java.lang.Exception: namespace 'markdown-to-hiccup.core' not found, compiling:(oz/core.clj:1:1) 

I have [markdown-to-hiccup "0.6.2"], [metasoarous/oz "1.5.6"] in my dependencies in project.clj.

**Comment by metasoarous** [comment]
Hi @NikolaF94. Thanks for reporting.

I haven't seen this particular problem before, but my bet is that it's the result of a dependency issue preventing `markdown-to-hiccup.core` from compiling. Can you please answer the following:

* What other dependencies you might have in your project? Particularly those which might conflict with those required by `markdown-to-hiccup.core`? FWIW, you can find a complete dependency tree like this: https://stackoverflow.com/questions/33093833/display-complete-dependency-tree-with-leiningen.
* If you run `lein clean`, and then run `lein repl` and `(require '[markdown-to-hiccup.core :as md2hc])` do you get any more detailed stack trace which might point out some vars that aren't being found?
* Any other useful information come to mind?

Thanks again for reporting and helping debug this.

**Comment by NikolaF94** [comment]
Hi @metasoarous , thanks for the fast response!

**This is my dependencies tree:**
[cheshire "5.8.1"]
   [com.fasterxml.jackson.core/jackson-core "2.9.6"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.9.6"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.9.6"]
   [tigris "0.1.1"]
 [clj-time "0.15.0"]
   [joda-time "2.10"]
 [clojure-complete "0.2.5" :exclusions [[org.clojure/clojure]]]
 [com.novemberain/monger "3.1.0"]
   [clojurewerkz/support "1.1.0"]
   [org.mongodb/mongodb-driver "3.3.0"]
     [org.mongodb/bson "3.3.0"]
     [org.mongodb/mongodb-driver-core "3.3.0"]
 [congomongo "1.0.1"]
   [org.clojure/data.json "0.2.6"]
   [org.mongodb/mongo-java-driver "3.8.1"]
 [damionjunk/nlp "0.3.0"]
   [edu.cmu.cs/ark-tweet-nlp "0.3.2"]
     [com.fasterxml.jackson.core/jackson-databind "2.0.0"]
       [com.fasterxml.jackson.core/jackson-annotations "2.0.0"]
     [com.google.guava/guava "10.0.1"]
     [com.twitter/twitter-text "1.6.1"]
     [commons-lang "2.3"]
     [edu.berkeley.nlp/berkeleyparser "r32"]
     [junit "4.8.2"]
     [net.sf.trove4j/trove4j "3.0.3"]
     [org.apache.commons/commons-math "2.1"]
     [org.apache.lucene/lucene-core "3.0.3"]
     [org.hamcrest/hamcrest-all "1.1"]
   [edu.stanford.nlp/stanford-corenlp "3.5.2"]
     [com.googlecode.efficient-java-matrix-library/ejml "0.23"]
     [com.io7m.xom/xom "1.2.10"]
       [xerces/xercesImpl "2.8.0"]
     [de.jollyday/jollyday "0.4.7"]
     [javax.json/javax.json-api "1.0"]
   [edu.stanford.nlp/stanford-corenlp "3.5.2" :classifier "models"]
 [incanter "1.9.3"]
   [incanter/incanter-charts "1.9.3"]
     [org.jfree/jfreechart "1.0.19"]
       [org.jfree/jcommon "1.0.23"]
   [incanter/incanter-core "1.9.3"]
     [net.mikera/core.matrix "0.52.0" :exclusions [[org.clojure/clojure]]]
     [net.mikera/vectorz-clj "0.44.1" :exclusions [[org.clojure/clojure]]]
       [net.mikera/clojure-utils "0.7.0"]
       [net.mikera/vectorz "0.62.0"]
         [net.mikera/mathz "0.3.0"]
         [net.mikera/randomz "0.3.0"]
         [us.bpsm/edn-java "0.4.6"]
     [net.sourceforge.parallelcolt/parallelcolt "0.10.1"]
       [com.github.rwl/JKLU "1.0.0"]
         [com.github.rwl/AMDJ "1.0.1"]
         [com.github.rwl/BTFJ "1.0.1"]
         [com.github.rwl/COLAMDJ "1.0.1"]
       [com.googlecode.netlib-java/netlib-java "0.9.3"]
       [net.sourceforge.csparsej/csparsej "1.1.1"]
       [net.sourceforge.jplasma/jplasma "1.2.0"]
         [net.sourceforge.f2j/arpack_combined_all "0.1"]
         [net.sourceforge.jplasma/core-lapack "0.1"]
       [net.sourceforge.jtransforms/jtransforms "2.4.0"]
       [net.sourceforge.parallelcolt/optimization "1.0"]
     [org.clojure/math.combinatorics "0.1.4" :exclusions [[org.clojure/clojure]]]
   [incanter/incanter-excel "1.9.3"]
     [org.apache.poi/poi-ooxml "3.16"]
       [com.github.virtuald/curvesapi "1.04"]
       [org.apache.poi/poi-ooxml-schemas "3.16"]
         [org.apache.xmlbeans/xmlbeans "2.6.0"]
           [stax/stax-api "1.0.1"]
       [org.apache.poi/poi "3.16"]
         [org.apache.commons/commons-collections4 "4.1"]
   [incanter/incanter-io "1.9.3"]
     [net.sf.opencsv/opencsv "2.3"]
     [org.clojure/data.csv "0.1.4" :exclusions [[org.clojure/clojure]]]
     [org.danlarkin/clojure-json "1.1" :exclusions [[org.clojure/clojure] [org.clojure/clojure-contrib]]]
   [incanter/incanter-latex "1.9.3"]
     [org.scilab.forge/jlatexmath "1.0.6"]
       [org.scilab.forge/jlatexmath-font-cyrillic "1.0.6"]
       [org.scilab.forge/jlatexmath-font-greek "1.0.6"]
   [incanter/incanter-mongodb "1.9.3"]
   [incanter/incanter-pdf "1.9.3"]
     [com.lowagie/itext "2.1.7" :exclusions [[org.bouncycastle/bctsp-jdk14] [bouncycastle/bcprov-jdk14] [bouncycastle/bcmail-jdk14]]]
     [org.bouncycastle/bctsp-jdk14 "1.46"]
       [org.bouncycastle/bcmail-jdk14 "1.46"]
       [org.bouncycastle/bcprov-jdk14 "1.46"]
   [incanter/incanter-sql "1.9.3"]
     [clojureql "1.0.5" :exclusions [[org.clojure/clojure]]]
       [mysql/mysql-connector-java "5.1.17"]
       [org.apache.derby/derby "10.1.1.0"]
       [org.clojure/core.incubator "0.1.4"]
       [postgresql "8.4-702.jdbc4"]
   [incanter/incanter-svg "1.9.3"]
     [org.apache.xmlgraphics/batik-awt-util "1.9.1"]
       [org.apache.xmlgraphics/xmlgraphics-commons "2.2"]
     [org.apache.xmlgraphics/batik-dom "1.9.1"]
       [org.apache.xmlgraphics/batik-css "1.9.1"]
       [org.apache.xmlgraphics/batik-ext "1.9.1"]
       [xalan "2.7.2"]
         [xalan/serializer "2.7.2"]
       [xml-apis/xml-apis-ext "1.3.04"]
       [xml-apis "1.3.04"]
     [org.apache.xmlgraphics/batik-svggen "1.9.1"]
     [org.apache.xmlgraphics/batik-util "1.9.1"]
       [org.apache.xmlgraphics/batik-constants "1.9.1"]
       [org.apache.xmlgraphics/batik-i18n "1.9.1"]
     [org.apache.xmlgraphics/batik-xml "1.9.1"]
   [incanter/incanter-zoo "1.9.3"]
   [swingrepl "1.3.0" :exclusions [[org.clojure/clojure] [org.clojure/clojure-contrib]]]
 [markdown-to-hiccup "0.6.2"]
   [hickory "0.7.1"]
     [quoin "0.1.2" :exclusions [[org.clojure/clojure]]]
     [viebel/codox-klipse-theme "0.0.1"]
   [markdown-clj "1.0.7"]
   [org.apache.commons/commons-lang3 "3.8.1"]
   [org.clojure/clojurescript "1.10.439"]
     [com.google.javascript/closure-compiler-unshaded "v20180805"]
       [args4j "2.0.26"]
       [com.google.code.findbugs/jsr305 "3.0.1"]
       [com.google.code.gson/gson "2.7"]
       [com.google.errorprone/error_prone_annotations "2.0.18"]
       [com.google.javascript/closure-compiler-externs "v20180805"]
       [com.google.jsinterop/jsinterop-annotations "1.0.0"]
       [com.google.protobuf/protobuf-java "3.0.2"]
     [org.clojure/google-closure-library "0.0-20170809-b9c14c6b"]
       [org.clojure/google-closure-library-third-party "0.0-20170809-b9c14c6b"]
     [org.mozilla/rhino "1.7R5"]
 [me.jhenrique/getoldtweets "1.1.0"]
   [org.apache.httpcomponents/httpclient "4.5"]
     [commons-logging "1.2"]
   [org.json/json "20151123"]
   [org.jsoup/jsoup "1.8.1"]
 [metasoarous/oz "1.5.6"]
   [aleph "0.4.6"]
     [byte-streams "0.2.4"]
       [primitive-math "0.1.6"]
     [io.netty/netty-codec-http "4.1.25.Final"]
     [io.netty/netty-codec "4.1.25.Final"]
     [io.netty/netty-handler-proxy "4.1.25.Final"]
       [io.netty/netty-codec-socks "4.1.25.Final"]
     [io.netty/netty-handler "4.1.25.Final"]
     [io.netty/netty-resolver-dns "4.1.25.Final"]
       [io.netty/netty-codec-dns "4.1.25.Final"]
     [io.netty/netty-resolver "4.1.25.Final"]
     [io.netty/netty-transport-native-epoll "4.1.25.Final"]
       [io.netty/netty-common "4.1.25.Final"]
       [io.netty/netty-transport-native-unix-common "4.1.25.Final"]
     [io.netty/netty-transport "4.1.25.Final"]
       [io.netty/netty-buffer "4.1.25.Final"]
     [manifold "0.1.8"]
       [io.aleph/dirigiste "0.1.5"]
     [org.clojure/tools.logging "0.4.1" :exclusions [[org.clojure/clojure]]]
   [bk/ring-gzip "0.3.0"]
   [clj-http "3.9.1"]
     [commons-codec "1.11" :exclusions [[org.clojure/clojure]]]
     [commons-io "2.6" :exclusions [[org.clojure/clojure]]]
     [org.apache.httpcomponents/httpasyncclient "4.1.3" :exclusions [[org.clojure/clojure]]]
       [org.apache.httpcomponents/httpcore-nio "4.4.6"]
     [org.apache.httpcomponents/httpclient-cache "4.5.5" :exclusions [[org.clojure/clojure]]]
     [org.apache.httpcomponents/httpcore "4.4.9" :exclusions [[org.clojure/clojure]]]
     [org.apache.httpcomponents/httpmime "4.5.5" :exclusions [[org.clojure/clojure]]]
     [potemkin "0.4.5" :exclusions [[org.clojure/clojure]]]
       [clj-tuple "0.2.2"]
       [riddley "0.1.12"]
     [slingshot "0.12.2" :exclusions [[org.clojure/clojure]]]
   [cljsjs/vega-embed "3.26.0-0"]
   [cljsjs/vega-lite "3.0.0-rc10-0"]
   [cljsjs/vega-tooltip "0.14.0-0"]
   [cljsjs/vega "4.4.0-0"]
   [com.clojure-goes-fast/lazy-require "0.1.1"]
   [com.cognitect/transit-clj "0.8.313"]
     [com.cognitect/transit-java "0.8.337"]
       [javax.xml.bind/jaxb-api "2.3.0"]
       [org.msgpack/msgpack "0.6.12"]
         [com.googlecode.json-simple/json-simple "1.1.1" :exclusions [[junit]]]
         [org.javassist/javassist "3.18.1-GA"]
   [com.cognitect/transit-cljs "0.8.256"]
     [com.cognitect/transit-js "0.8.846"]
   [com.taoensso/sente "1.13.1"]
     [com.taoensso/encore "2.96.0"]
       [com.taoensso/truss "1.5.0"]
     [com.taoensso/timbre "4.10.0"]
       [io.aviso/pretty "0.1.33"]
     [org.clojure/tools.reader "1.3.0"]
   [commonmark-hiccup "0.1.0"]
     [com.atlassian.commonmark/commonmark "0.8.0"]
   [compojure "1.6.1"]
     [clout "2.2.1"]
       [instaparse "1.4.8" :exclusions [[org.clojure/clojure]]]
     [medley "1.0.0"]
     [org.clojure/tools.macro "0.1.5"]
     [ring/ring-codec "1.1.0"]
   [hiccup "1.0.5"]
   [io.forward/yaml "1.0.9"]
     [org.yaml/snakeyaml "1.19"]
   [irresponsible/tentacles "0.6.3"]
     [com.cemerick/url "0.1.1"]
       [pathetic "0.5.0"]
         [com.cemerick/clojurescript.test "0.0.4"]
     [environ "1.1.0"]
   [org.clojars.didiercrunch/clojupyter "0.1.5"]
     [beckon "0.1.1"]
     [cider/cider-nrepl "0.15.1"]
       [org.tcrawley/dynapath "0.2.5" :exclusions [[org.clojure/clojure]]]
     [com.cemerick/pomegranate "0.3.1"]
       [org.apache.maven.wagon/wagon-http "2.2"]
         [org.apache.maven.wagon/wagon-http-shared4 "2.2"]
       [org.apache.maven.wagon/wagon-provider-api "2.2"]
       [org.apache.maven/maven-aether-provider "3.0.4"]
         [org.apache.maven/maven-model-builder "3.0.4"]
           [org.codehaus.plexus/plexus-interpolation "1.14"]
         [org.apache.maven/maven-model "3.0.4"]
         [org.apache.maven/maven-repository-metadata "3.0.4"]
         [org.codehaus.plexus/plexus-component-annotations "1.5.5" :exclusions [[junit]]]
         [org.codehaus.plexus/plexus-utils "2.0.6"]
       [org.sonatype.aether/aether-api "1.13.1"]
       [org.sonatype.aether/aether-connector-file "1.13.1"]
       [org.sonatype.aether/aether-connector-wagon "1.13.1" :exclusions [[org.codehaus.plexus/plexus-utils]]]
         [org.codehaus.plexus/plexus-classworlds "2.4"]
         [org.sonatype.sisu/sisu-inject-plexus "2.2.3"]
           [org.sonatype.sisu/sisu-inject-bean "2.2.3"]
             [org.sonatype.sisu/sisu-guice "3.0.3" :classifier "no_aop" :exclusions [[javax.inject] [aopalliance]]]
       [org.sonatype.aether/aether-impl "1.13.1"]
         [org.sonatype.aether/aether-spi "1.13.1"]
       [org.sonatype.aether/aether-util "1.13.1"]
     [net.cgrand/parsley "0.9.3" :exclusions [[org.clojure/clojure]]]
       [net.cgrand/regex "1.1.0"]
     [net.cgrand/sjacket "0.1.1" :exclusions [[org.clojure/clojure] [net.cgrand.parsley]]]
     [org.clojure/data.codec "0.1.0"]
     [org.clojure/java.jdbc "0.3.7"]
     [org.clojure/tools.nrepl "0.2.12"]
     [org.xerial/sqlite-jdbc "3.7.2"]
     [org.zeromq/cljzmq "0.1.4" :exclusions [[org.zeromq/jzmq]]]
     [org.zeromq/jeromq "0.3.4"]
     [pandect "0.5.4"]
       [org.bouncycastle/bcprov-jdk15on "1.52" :exclusions [[org.clojure/clojure]]]
   [org.clojure/core.async "0.4.490"]
     [org.clojure/tools.analyzer.jvm "0.7.2"]
       [org.clojure/core.memoize "0.5.9"]
         [org.clojure/core.cache "0.6.5"]
           [org.clojure/data.priority-map "0.0.7"]
       [org.clojure/tools.analyzer "0.6.9"]
       [org.ow2.asm/asm-all "4.2"]
   [org.clojure/spec.alpha "0.2.176"]
   [org.flatland/ordered "1.5.7"]
     [org.flatland/useful "0.11.6"]
   [reagent "0.8.1"]
     [cljsjs/create-react-class "15.6.3-0"]
     [cljsjs/react-dom-server "16.3.2-0"]
     [cljsjs/react-dom "16.3.2-0"]
     [cljsjs/react "16.3.2-0"]
   [ring-cljsjs "0.1.0"]
   [ring/ring-defaults "0.3.2"]
     [javax.servlet/javax.servlet-api "3.1.0"]
     [ring/ring-anti-forgery "1.3.0"]
     [ring/ring-headers "0.3.0"]
     [ring/ring-ssl "0.3.0"]
   [ring "1.7.1"]
     [ring/ring-core "1.7.1"]
       [commons-fileupload "1.3.3"]
       [crypto-equality "1.0.0"]
       [crypto-random "1.2.0"]
     [ring/ring-devel "1.7.1"]
       [clj-stacktrace "0.2.8"]
       [ns-tracker "0.3.1"]
         [org.clojure/java.classpath "0.2.3"]
         [org.clojure/tools.namespace "0.2.11"]
     [ring/ring-jetty-adapter "1.7.1"]
       [org.eclipse.jetty/jetty-server "9.4.12.v20180830"]
         [org.eclipse.jetty/jetty-http "9.4.12.v20180830"]
           [org.eclipse.jetty/jetty-util "9.4.12.v20180830"]
         [org.eclipse.jetty/jetty-io "9.4.12.v20180830"]
     [ring/ring-servlet "1.7.1"]
 [nrepl "0.5.3" :exclusions [[org.clojure/clojure]]]
   [nrepl/bencode "1.0.0"]
 [org.clojure/clojure "1.8.0"]
**I did get this tho:**
Possibly confusing dependencies found:
[org.clojure/clojure "1.8.0"]
 overrides
[metasoarous/oz "1.5.6"] -> [org.flatland/ordered "1.5.7"] -> [org.flatland/useful "0.11.6"] -> [org.clojure/clojure "1.9.0"]
 and
[metasoarous/oz "1.5.6"] -> [markdown-to-hiccup "0.6.1"] -> [markdown-clj "1.0.7"] -> [org.clojure/clojure "1.9.0"]
 and
[markdown-to-hiccup "0.6.2"] -> [markdown-clj "1.0.7"] -> [org.clojure/clojure "1.9.0"]
 and
[metasoarous/oz "1.5.6"] -> [org.flatland/ordered "1.5.7"] -> [org.clojure/clojure "1.9.0"]
 and
[metasoarous/oz "1.5.6"] -> [markdown-to-hiccup "0.6.1"] -> [org.clojure/clojure "1.9.0"]
 and
[metasoarous/oz "1.5.6"] -> [reagent "0.8.1"] -> [org.clojure/clojure "1.9.0"]
 and
[metasoarous/oz "1.5.6"] -> [com.taoensso/sente "1.13.1"] -> [org.clojure/clojure "1.9.0"]
 and
[markdown-to-hiccup "0.6.2"] -> [org.clojure/clojure "1.10.0"]
 and
[metasoarous/oz "1.5.6"] -> [org.clojure/clojure "1.10.0"]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [org.clojure/clojure]]
[markdown-to-hiccup "0.6.2" :exclusions [org.clojure/clojure]]

[me.jhenrique/getoldtweets "1.1.0"] -> [org.jsoup/jsoup "1.8.1"]
 overrides
[metasoarous/oz "1.5.6"] -> [markdown-to-hiccup "0.6.1"] -> [hickory "0.7.1"] -> [org.jsoup/jsoup "1.9.2"]
 and
[markdown-to-hiccup "0.6.2"] -> [hickory "0.7.1"] -> [org.jsoup/jsoup "1.9.2"]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [org.jsoup/jsoup]]
[markdown-to-hiccup "0.6.2" :exclusions [org.jsoup/jsoup]]

[me.jhenrique/getoldtweets "1.1.0"] -> [org.apache.httpcomponents/httpclient "4.5"]
 overrides
[metasoarous/oz "1.5.6"] -> [irresponsible/tentacles "0.6.3"] -> [clj-http "3.9.1"] -> [org.apache.httpcomponents/httpmime "4.5.5" :exclusions [org.clojure/clojure]] -> [org.apache.httpcomponents/httpclient "4.5.5"]
 and
[metasoarous/oz "1.5.6"] -> [irresponsible/tentacles "0.6.3"] -> [clj-http "3.9.1"] -> [org.apache.httpcomponents/httpasyncclient "4.1.3" :exclusions [org.clojure/clojure]] -> [org.apache.httpcomponents/httpclient "4.5.3"]
 and
[metasoarous/oz "1.5.6"] -> [irresponsible/tentacles "0.6.3"] -> [clj-http "3.9.1"] -> [org.apache.httpcomponents/httpclient-cache "4.5.5" :exclusions [org.clojure/clojure]] -> [org.apache.httpcomponents/httpclient "4.5.5"]
 and
[metasoarous/oz "1.5.6"] -> [irresponsible/tentacles "0.6.3"] -> [clj-http "3.9.1"] -> [org.apache.httpcomponents/httpclient "4.5.5" :exclusions [org.clojure/clojure]]
 and
[metasoarous/oz "1.5.6"] -> [clj-http "3.9.1"] -> [org.apache.httpcomponents/httpmime "4.5.5" :exclusions [org.clojure/clojure]] -> [org.apache.httpcomponents/httpclient "4.5.5"]
 and
[metasoarous/oz "1.5.6"] -> [clj-http "3.9.1"] -> [org.apache.httpcomponents/httpasyncclient "4.1.3" :exclusions [org.clojure/clojure]] -> [org.apache.httpcomponents/httpclient "4.5.3"]
 and
[metasoarous/oz "1.5.6"] -> [clj-http "3.9.1"] -> [org.apache.httpcomponents/httpclient-cache "4.5.5" :exclusions [org.clojure/clojure]] -> [org.apache.httpcomponents/httpclient "4.5.5"]
 and
[metasoarous/oz "1.5.6"] -> [clj-http "3.9.1"] -> [org.apache.httpcomponents/httpclient "4.5.5" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [org.apache.httpcomponents/httpclient]]

[metasoarous/oz "1.5.6"] -> [compojure "1.6.1"] -> [ring/ring-codec "1.1.0"]
 overrides
[metasoarous/oz "1.5.6"] -> [ring "1.7.1"] -> [ring/ring-jetty-adapter "1.7.1"] -> [ring/ring-servlet "1.7.1"] -> [ring/ring-core "1.7.1"] -> [ring/ring-codec "1.1.1"]
 and
[metasoarous/oz "1.5.6"] -> [ring "1.7.1"] -> [ring/ring-servlet "1.7.1"] -> [ring/ring-core "1.7.1"] -> [ring/ring-codec "1.1.1"]
 and
[metasoarous/oz "1.5.6"] -> [ring "1.7.1"] -> [ring/ring-jetty-adapter "1.7.1"] -> [ring/ring-core "1.7.1"] -> [ring/ring-codec "1.1.1"]
 and
[metasoarous/oz "1.5.6"] -> [ring "1.7.1"] -> [ring/ring-devel "1.7.1"] -> [ring/ring-core "1.7.1"] -> [ring/ring-codec "1.1.1"]
 and
[metasoarous/oz "1.5.6"] -> [ring "1.7.1"] -> [ring/ring-core "1.7.1"] -> [ring/ring-codec "1.1.1"]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [ring/ring-codec]]

[metasoarous/oz "1.5.6"] -> [org.clojars.didiercrunch/clojupyter "0.1.5"] -> [org.clojure/data.codec "0.1.0"]
 overrides
[metasoarous/oz "1.5.6"] -> [irresponsible/tentacles "0.6.3"] -> [org.clojure/data.codec "0.1.1"]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [org.clojure/data.codec]]

[metasoarous/oz "1.5.6"] -> [org.clojars.didiercrunch/clojupyter "0.1.5"] -> [org.clojure/tools.nrepl "0.2.12"]
 overrides
[metasoarous/oz "1.5.6"] -> [org.clojars.didiercrunch/clojupyter "0.1.5"] -> [cider/cider-nrepl "0.15.1"] -> [org.clojure/tools.nrepl "0.2.13" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [org.clojure/tools.nrepl]]

[damionjunk/nlp "0.3.0"] -> [edu.cmu.cs/ark-tweet-nlp "0.3.2"] -> [com.google.guava/guava "10.0.1"]
 overrides
[metasoarous/oz "1.5.6"] -> [irresponsible/tentacles "0.6.3"] -> [com.cemerick/url "0.1.1"] -> [pathetic "0.5.0"] -> [com.cemerick/clojurescript.test "0.0.4"] -> [org.clojure/clojurescript "0.0-1586"] -> [com.google.javascript/closure-compiler "r2180"] -> [com.google.guava/guava "13.0.1"]
 and
[metasoarous/oz "1.5.6"] -> [markdown-to-hiccup "0.6.1"] -> [hickory "0.7.1"] -> [org.clojure/clojurescript "1.9.293"] -> [com.google.javascript/closure-compiler-unshaded "v20160911"] -> [com.google.guava/guava "19.0"]
 and
[markdown-to-hiccup "0.6.2"] -> [hickory "0.7.1"] -> [org.clojure/clojurescript "1.9.293"] -> [com.google.javascript/closure-compiler-unshaded "v20160911"] -> [com.google.guava/guava "19.0"]
 and
[metasoarous/oz "1.5.6"] -> [markdown-to-hiccup "0.6.1"] -> [org.clojure/clojurescript "1.10.238"] -> [com.google.javascript/closure-compiler-unshaded "v20180204"] -> [com.google.guava/guava "22.0"]
 and
[markdown-to-hiccup "0.6.2"] -> [org.clojure/clojurescript "1.10.439"] -> [com.google.javascript/closure-compiler-unshaded "v20180805"] -> [com.google.guava/guava "25.1-jre"]
 and
[com.novemberain/monger "3.1.0"] -> [clojurewerkz/support "1.1.0"] -> [com.google.guava/guava "18.0"]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [com.google.guava/guava]]
[markdown-to-hiccup "0.6.2" :exclusions [com.google.guava/guava]]
[com.novemberain/monger "3.1.0" :exclusions [com.google.guava/guava]]

[metasoarous/oz "1.5.6"] -> [clj-http "3.9.1"] -> [potemkin "0.4.5" :exclusions [org.clojure/clojure]] -> [riddley "0.1.12"]
 overrides
[metasoarous/oz "1.5.6"] -> [aleph "0.4.6"] -> [byte-streams "0.2.4"] -> [manifold "0.1.8"] -> [riddley "0.1.14"]
 and
[metasoarous/oz "1.5.6"] -> [aleph "0.4.6"] -> [manifold "0.1.8"] -> [riddley "0.1.14"]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [riddley]]

[markdown-to-hiccup "0.6.2"] -> [org.clojure/clojurescript "1.10.439"] -> [com.google.javascript/closure-compiler-unshaded "v20180805"] -> [args4j "2.0.26"]
 overrides
[metasoarous/oz "1.5.6"] -> [markdown-to-hiccup "0.6.1"] -> [org.clojure/clojurescript "1.10.238"] -> [com.google.javascript/closure-compiler-unshaded "v20180204"] -> [args4j "2.33"]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [args4j]]

[markdown-to-hiccup "0.6.2"] -> [org.clojure/clojurescript "1.10.439"] -> [com.google.javascript/closure-compiler-unshaded "v20180805"] -> [com.google.errorprone/error_prone_annotations "2.0.18"]
 overrides
[markdown-to-hiccup "0.6.2"] -> [org.clojure/clojurescript "1.10.439"] -> [com.google.javascript/closure-compiler-unshaded "v20180805"] -> [com.google.guava/guava "25.1-jre"] -> [com.google.errorprone/error_prone_annotations "2.1.3"]

Consider using these exclusions:
[markdown-to-hiccup "0.6.2" :exclusions [com.google.errorprone/error_prone_annotations]]

[markdown-to-hiccup "0.6.2"] -> [org.clojure/clojurescript "1.10.439"] -> [com.google.javascript/closure-compiler-unshaded "v20180805"] -> [com.google.code.findbugs/jsr305 "3.0.1"]
 overrides
[markdown-to-hiccup "0.6.2"] -> [org.clojure/clojurescript "1.10.439"] -> [com.google.javascript/closure-compiler-unshaded "v20180805"] -> [com.google.guava/guava "25.1-jre"] -> [com.google.code.findbugs/jsr305 "3.0.2"]

Consider using these exclusions:
[markdown-to-hiccup "0.6.2" :exclusions [com.google.code.findbugs/jsr305]]

[metasoarous/oz "1.5.6"] -> [org.clojars.didiercrunch/clojupyter "0.1.5"] -> [com.cemerick/pomegranate "0.3.1"] -> [org.apache.maven/maven-aether-provider "3.0.4"] -> [org.codehaus.plexus/plexus-utils "2.0.6"]
 overrides
[metasoarous/oz "1.5.6"] -> [org.clojars.didiercrunch/clojupyter "0.1.5"] -> [com.cemerick/pomegranate "0.3.1"] -> [org.apache.maven.wagon/wagon-http "2.2"] -> [org.apache.maven.wagon/wagon-http-shared4 "2.2"] -> [org.apache.maven.wagon/wagon-provider-api "2.2"] -> [org.codehaus.plexus/plexus-utils "3.0"]
 and
[metasoarous/oz "1.5.6"] -> [org.clojars.didiercrunch/clojupyter "0.1.5"] -> [com.cemerick/pomegranate "0.3.1"] -> [org.apache.maven.wagon/wagon-http "2.2"] -> [org.apache.maven.wagon/wagon-provider-api "2.2"] -> [org.codehaus.plexus/plexus-utils "3.0"]
 and
[metasoarous/oz "1.5.6"] -> [org.clojars.didiercrunch/clojupyter "0.1.5"] -> [com.cemerick/pomegranate "0.3.1"] -> [org.apache.maven.wagon/wagon-provider-api "2.2"] -> [org.codehaus.plexus/plexus-utils "3.0"]

Consider using these exclusions:
[metasoarous/oz "1.5.6" :exclusions [org.codehaus.plexus/plexus-utils]]

**Comment by NikolaF94** [comment]
If you run lein clean, and then run lein repl and (require '[markdown-to-hiccup.core :as md2hc]) do you get any more detailed stack trace which might point out some vars that aren't being found?

-This is what I get: CompilerException java.lang.ExceptionInInitializerError, compiling:(markdown_to_hiccup/core.cljc:1:1)

**Comment by metasoarous** [comment]
Hmm... Is it possible for you to upgrade to Clojure 1.10?

**Comment by NikolaF94** [comment]
I tried but then when I use require and :import in namespace binding it throws multiple exceptions:

Syntax error macroexpanding clojure.core/ns at (form-init4088421037190878440.clj:1:1).
require - failed: #{:refer-clojure} at: [:ns-clauses :refer-clojure :clause] spec: :clojure.core.specs.alpha/ns-refer-clojure
require - failed: #{:require} at: [:ns-clauses :require :clause] spec: :clojure.core.specs.alpha/ns-require
require - failed: #{:import} at: [:ns-clauses :import :clause] spec: :clojure.core.specs.alpha/ns-import
require - failed: #{:use} at: [:ns-clauses :use :clause] spec: :clojure.core.specs.alpha/ns-use
require - failed: #{:refer} at: [:ns-clauses :refer :clause] spec: :clojure.core.specs.alpha/ns-refer
require - failed: #{:load} at: [:ns-clauses :load :clause] spec: :clojure.core.specs.alpha/ns-load
require - failed: #{:gen-class} at: [:ns-clauses :gen-class :clause] spec: :clojure.core.specs.alpha/ns-gen-class

**Comment by NikolaF94** [comment]
And also, when I type (require [oz. - I don't get ''core'' as an option after ''oz.''.

**Comment by metasoarous** [comment]
Can you please show me your name binding?

**Comment by NikolaF94** [comment]
Of course:

(ns read-tweets
  (:import (me.jhenrique.main Main))
  (:import org.bson.types.ObjectId)
  (:require [monger.core :as mg]
            [monger.collection :as mc])
  (require [damionjunk.nlp.stanford :refer :all])
  (require [clj-time.core :as t])
  (require [clj-time.format :as f])
  (:require [cheshire.core :refer :all])
  (require [clj-time.coerce :as c])
  (require [markdown-to-hiccup.core])


  (:import [java.util Calendar Date GregorianCalendar TimeZone]
           [java.sql Timestamp]
           (java.time.format DateTimeFormatter)
           (java.time ZonedDateTime)))

**Comment by metasoarous** [comment]
@NikolaF94 I think your problem here is that `(require ...)` is not supported in `ns` forms (only `(:require ...)`). It was somewhat "accidentally" supported on older version of Clojure, but this was made more strict with 1.9 IIRC. Also, less important (I think), but typical style is to only use a single `(:require ...)` form with all requires.

Would you please try updating your namespace form, and see if you're able to compile with Clojure 1.10 afterwards?

Thanks in advance.

**Comment by NikolaF94** [comment]
@metasoarous 

I updated the namespace form and upgraded to Clojure 1.10.0 and it works!! Thank you! :)
Looks like it was Clojure 1.8.0 that was problematic...

**Comment by metasoarous** [comment]
Hi @NikolaF94! Just going through and closing some old issues. Thanks for reporting back on this!
