### ISSUE TITLE
Incorrect vega-lite version bundled with 16.0-alpha2

### ISSUE THREAD

**Issue by jimmyhmiller** [metasoarous/oz#60]
I was attempting to use a [facet encoding channel](https://vega.github.io/vega-lite/docs/facet.html#facet-encoding) with the new alpha because I saw it was on an updated vega-lite that supported it. But I kept having trouble when using `oz/view!`. I would get an error in the console that `facet-encoding is dropped as facet is not a valid encoding channel.`. 

If I open in the editor it works perfectly fine. I also can use `oz/html`. Since that has script tags pointing to the correct version it also works. 

It seems like javascript might not have been rebuilt when releasing the new jar. 

If you need any more information for reproduction, let me know.

**Comment by metasoarous** [comment]
Hi @jimmyhmiller. Thanks for reporting this.

Can you please open up your console and report back the value of `vl.version`? For me, it returns 3.2.0, as I'd expect.

If you're getting something other than 3.2.0, is there a chance that you have an explicit dependency on some other version of `cljsjs/vega-lite` in your `project.clj`? If not, can you try running `lein clean` to see if that fixes things?

Thanks in advance

**Comment by jimmyhmiller** [comment]
`lein clean` and reloading with cache fixed it. Before I did that I had version `3.0.0-rc10`now it is correct at `3.0.2`. Sorry I didn't think about lein clean before submitting. 

Thanks for this awesome project. It has been super useful for me with visualizing a bunch of different data.

**Comment by metasoarous** [comment]
Wonderful! And not a problem. Glad we have things working for you.

Thanks again, both for using the library and for the kind words.
