### ISSUE TITLE
Web server broken after using update-cljsjs.sh

### ISSUE THREAD

**Issue by kanaka** [metasoarous/oz#72]
I would like to update update my vega-lite version to 4.0.0-beta.0 (just released a couple days ago) so that I can use labelExpr values (use Vega expression to set the value of each axis label item). I'm not really interested in pushing packages out (and this is attempting to use a beta version of vega-lite anyhow). So I'm just trying to build, install and use locally. However, when I do the update using update-cljsjs.sh, bump the versions in project.def to match, and then lein install a new version of Oz, it seems to break the embedded webserver in my project that uses it. And the breakage seems to happen even if I attempt to do it with the original versions so I suspect something is getting corruption during the packaging/install process.

In my REPL I get the normal startup messages:

```
19-08-08 06:12:27 kanaka INFO [oz.core:75] - Starting up server on port 10666
19-08-08 06:12:27 kanaka INFO [oz.server:139] - Web server is running at `http://localhost:10666/`
[23251:23251:0808/011227.990318:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
```

But in the browser I see "OZ / pay no attention" and the JS console has the following error message:

```
localhost/:1 Refused to execute script from 'http://localhost:10666/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

If I just directly curl `'http://localhost:10666/js/compiled/oz.js` it redirects with a 302 to / which gives the original HTML which explains the MIME type complaint.

Have you seen this issue before? Anything I'm doing wrong regarding local use?

**Comment by kanaka** [comment]
After reading through `project.clj` I realized that I wasn't packaging up everything with a simple `lein install`. So I did `lein "jar!"` and then `lein install` and that fixed the initial breakage.

I'll close this, but it might be worth noting on the README how to update the vega components versions and use them locally without any deployment. Here is the process I had to use:

```
# edit versions in bin/update-cljsjs.sh
./bin/update-cljsjs.sh
# edit versions in src/clj/oz/core.clj
# edit versions in resources/oz/public/index.html
# edit versions in project.clj including oz version
lein "jar!"
lein install
# update project.clj of project that uses oz to use update oz version
```

I'm not certain all of those steps are necessary, but it would be nice if the whole process was a bit more automated or at least documented (especially the version update of index.html which definitely was necessary before it worked for me).

Thanks for the great project!

**Comment by metasoarous** [comment]
Hey @kanaka! Thanks for reporting this, and more generally for your interest in and support of the project!

I'll try to get around to adding this to the README, but please feel free to PR away at the docs if you'd like to contribute. The `update-cljsjs.sh` script suffers from some complexity inherent to working with cljsjs.

FWIW, I just pushed some cljsjs updates last night, which hopefully will be getting merged soon. If there's useful stuff I should know about, and if it works well for you, I'll try to push out another update with the beta as well.

Thanks again!

Chris
