### ISSUE TITLE
Should Oz control dependencies more tighly to prevent downstream dependency conflicts?

### ISSUE THREAD

**Issue by teodorlu** [metasoarous/oz#73]
**Context**: Oz has quite a few dependencies. Down the line, that leads to dependency conflicts where libraries Oz depends on again depend on the same library of different versions. With leiningen, `lein deps :tree` gives an overview of which dependencies are in conflict, along with the recursive dependency tree.

**User need**: I want to use Oz in my project. However, a recursive Oz dependency conflicted with Ring versions (I think). But the `lein deps :tree` output was mostly full of Oz's own dependency conflicts, so it was hard for me to see the conflicts I needed to fix.

**Suggestion**: Should Oz be more specific about choosing versions of dependent libraries?

---

I've done a little bit of research. As a user of the Oz library, the `project.clj` below [1] gave me a clean output of `lein deps :tree`, and worked in practice from a quick set of checks. If we were to adapt it to be used from Oz directly, we would have to place exclusions at the relevant libraries, but that shouldn't be much work.

Is there any interest in doing this? Or might there be a reason why `:exclusions` aren't used per now that I'm ignoring?

Thanks!

Teodor

```clojure
;; [1]
(defproject th/mini.oz2 "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]

                 ;; Oz and dependency overrides
                 [metasoarous/oz "1.6.0-alpha3"
                  :exclusions [ring/ring-codec
                               org.clojure/clojurescript
                               clj-time
                               org.clojure/data.codec
                               org.clojure/tools.nrepl
                               com.google.errorprone/error_prone_annotations
                               com.google.code.findbugs/jsr305
                               riddley
                               org.codehaus.plexus/plexus-utils
                               ]]

                 ;; Just pick the latest versions, and see if that works.
                 [ring/ring-codec "1.1.1"]
                 [org.clojure/clojurescript "1.10.520"]
                 [clj-time "0.15.2"]
                 [org.clojure/data.codec "0.1.1"]
                 [org.clojure/tools.nrepl "0.2.13"]
                 [org.yaml/snakeyaml "1.24"]
                 [com.google.errorprone/error_prone_annotations "2.1.3"]
                 [com.google.code.findbugs/jsr305 "3.0.2"]
                 [riddley "0.1.12"]
                 [org.codehaus.plexus/plexus-utils "3.2.1"]

                 ;; Seems to work.

                 ]
  :repl-options {:init-ns th.mini.oz2})
```

**Comment by metasoarous** [comment]
Hi @teodorlu. Thanks for laying out this issue in such detail.

I'd absolutely be interested in taking a pull request which cleans this up. My one addendum to your proposal (which maybe you had in mind anyway) would be that for anything in your exclusion list above, we should be making an explicit dependency in Oz's `project.clj` (rather than rely on the version specified by a dependent which Oz does explicitly specify). But yes, I'm all for cleaning up the dependencies if that helps folks overcome issues. I've seen a couple of dependency issues pop up with Oz in other projects, and you're right that this step would help clean things up.

Thanks again!

**Comment by teodorlu** [comment]
Glad to hear that!

I'll think about it for a little while. If it goes anywhere, I'll send a PR for review.

**Comment by metasoarous** [comment]
Hi @teodorlu. Just checking in to see if you've thought about this any more, and to let you know that I'll be releasing Oz as a regular jar instead of an uberjar (see #78) in case that helps you at all.

Thanks again.

**Comment by teodorlu** [comment]
Hello @metasoarous,

Thanks for keeping me in the loop. I've been keeping this in the back of my mind, to some extent looking to pick it back up the next time the need arose. I don't know the intricacies of jar packaging vs uberjar packaging.

To me, it seems right to re-visit this after switching to jar packaging.

Teodor

**Comment by metasoarous** [comment]
Hi @teodorlu. Please take a look at #78 again. Specifically, I just released `[metasoarous/oz "1.6.0-alpha6-SNAPSHOT"]`, which is built without an `uberjar`, and may help with some of these dependency issues.

Please let me know if you have a chance to take it for a spin.

Thanks!

**Comment by teodorlu** [comment]
Hey! Normal jar without deps sounds great.

I'm a bit out of context at the moment, not having worked with Oz since the summer. But I'll try to give it another shot.

I'm glad to be kept in the loop, and feel free to keep pinging me any time :)

Teodor

**Comment by teodorlu** [comment]
Hey @metasoarous,

I tried to get my original issue tested. Here's what I did:

1. Try to reproduce my original problem
2. See if my original workaround fixed it
3. Bump to `metasorous/oz "1.6.0-alpha6-SNAPSHOT"`

Results:

I was unable to reproduce the original issue. My small test code ran fine in all cases.

Conclusions:

- I suggest we close this issue, unless you have objections
- Packaging Oz as a jar seems to me like the right way to go. Thanks for your continued effort!

Teodor

**Comment by damionjunk** [comment]
I just ran into this today trying to get nREPL working with shadow-cljs and this project. I added the several exclusions, including `cider/cider-nrepl` which seemed to fix my issue (https://nrepl.org/nrepl/troubleshooting.html) 

I thought I'd comment incase anyone else encounters it.

**Comment by metasoarous** [comment]
Hi @damionjunk. Thanks for submitting this!

I've removed the implicit dependency on clojupyter, which seems to have been responsible for a lot of these issues in the past, and I suspect may be what was requiring cider in this case (it's not an explicit dependency of Oz's, at least). It's probably still a bit buggy, but please take a look at `1.6.0-alpha7-SNAPSHOT` and let me know if you still observe the problem.

Thanks again!

**Comment by metasoarous** [comment]
I'm going to close this issue, as I think the switch from uberjar to jar (and making clojupyter an optional dependency) has improved things quite a bit. There may still be some issues with those trying to use Oz with Clojupyter (since the latter does AOT compilation, which makes these dependency issues quite a bit more thorny), but it sounds like there's some effort to improve that as well (see https://github.com/clojupyter/clojupyter/issues/141 and https://github.com/clojupyter/clojupyter/issues/129), and ultimately I think we've done most of what we can do for now.

Thanks again folks!
