### ISSUE TITLE
bug? tooltip content data doesn't show all variables

### ISSUE THREAD

**Issue by keesterbrugge** [metasoarous/oz#75]
Hi, 

I think I've stumbled upon a bug. After evaluating the following code

``` clojure
(oz/view!
 {:data {:values [{:x 1 :y 1 :z 1} {:x 3 :y 3}]}
  :hconcat [{:mark {:type :point :tooltip {:content :data}}
             :encoding {:x {:field :x :type :quantitative}
                        :y {:field :y :type :quantitative}}}
            {:mark {:type :line :point true :tooltip {:content :data}}
             :encoding {:x {:field :x :type :quantitative}
                        :y {:field :y :type :quantitative}}}]})
```
you'd expect to see the tooltips in both plots to include info on the `:z` variable when hovering over the point `{:x 1 :y 1}`, however it doesn't work correctly in the plot with the lines and points. 

<img width="720" alt="Screenshot 2019-08-21 at 14 59 17" src="https://user-images.githubusercontent.com/6086439/63435880-faae3400-c427-11e9-8b24-ed97397a8989.png">

When you view the viz in the vega editor [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYMAAzbl0wCnR9blZk+GzYOjUNSE1rTBxgSCyxVh1sMABtaoAPSDAcAEYwVSgATw6sHr7IAC9GroBfPrahsGlegfnpKbAAXRmQUsR4ZQK8eY0WyAxdAGtG6rx+2MbIAI9D0bxubjEjQivIPaU8ZD+93KeEwUy2EEgAL2mg81CuGgh7SqkBSjGQYk093aL1uyHuAEdWCEjCCjFRIOCIMtkaj0ZjTIMcXdTITicxrIxyVMNGD1BBqmdLsibsyoBIlHjRo9ATg8Lp6i83h8DN9fv8ZVoKhTKZClNDYfCqVAkWBqrSMVi1FARXiWUS-uyyXjKRDBjS0RaGVbIDaCfaSRyuTypusQFMgA) it does work correct in both plots.

I couldn't figure out what's going wrong, hopefully somebody can help. 

Thanks for the library Christopher, it's making plotting much more enjoyable!

**Comment by metasoarous** [comment]
Hi @keesterbrugge. Thanks for reporting, and for the kind words :-)

There's a good chance this is the result of a slightly older Vega version. I'm going to be updating in a few days, and encourage you to give it a whirl then.

Stay tuned, and thanks again!

**Comment by MawiraIke** [comment]
Seems like this was fixed with the vega update. 

![Screenshot from 2020-03-22 00-56-27](https://user-images.githubusercontent.com/38689046/77237332-65029f00-6bd8-11ea-8764-5f9a5c334c74.png)

**Comment by metasoarous** [comment]
Excellent! Thanks for the report @MawiraIke.

@keesterbrugge Please feel free to reopen if you're still seeing this issue in your context.
