### ISSUE TITLE
fullscreen / fill available space

### ISSUE THREAD

**Issue by awb99** [metasoarous/oz#76]
I would like to have the charts fill the remaining space they have available. Also it would be cool to be able to view a given chart fullscreen (for more details). I played around with the vega settings "autosize": { "type": "fit" } but they seem not to get me what I want.

Any ideas? I think this is a very valid requirement for pretty much any chart that it can become in some way responsive and optimally use available screen real estate.

Thanks!

**Comment by metasoarous** [comment]
Hi @awb99; Thanks for raising this issue!

However, I'm closing this as a duplicated of #74. Please feel free to chime in there.

As long as we're able to get `autosize` working, I'd imagine it would function well with fullscreen mode (by hitting F11).

If you really want to make a case specifically for some kind of auto-fullscreen option support, feel free to either reopen this issue with edited title/description, or just open a new issue.
