### ISSUE TITLE
Gradient area not working?

### ISSUE THREAD

**Issue by alex314159** [metasoarous/oz#77]
Trying to plot the following - the area appears white, whereas if I display in vega editor, it is shaded properly

    {:data {:values [{:x 1, :y 2} {:x 2, :y 4}]},
     :mark
     {:type "area",
      :line {:color "darkgreen"},
      :color
      {:x1 1,
       :y1 1,
       :x2 1,
       :y2 0,
       :gradient "linear",
       :stops
       [{:offset 0, :color "white"}
        {:offset 1, :color "darkgreen"}]}},
     :encoding
     {:x {:field "x", :type "quantitative"},
      :y {:field "y", :type "quantitative"}}}

**Comment by metasoarous** [comment]
I'll bet this just has to do with the vega version.

**Comment by alex314159** [comment]
You're right, as part of moving from figwheel to shadow-cljs I had to install npm and vega / vega-lite independently, and it's now working. Closing the issue. Thanks!
