### ISSUE TITLE
Publishing the library as an uberjar creates conflicts

### ISSUE THREAD

**Issue by stathissideris** [metasoarous/oz#78]
Usually, Clojure libraries are published as regular jars (not uberjars), and rely on leiningen (or tools-deps) to resolve and retreive the transitive of the library. In the case of Oz, the library is packaged and published as an uberjar which can create conflicts for consuming projects.

Specifically, I ran into [such an issue](https://github.com/juxt/pack.alpha/issues/64) while trying to make an uberjar using juxt.pack for a project that depends on oz. As you can see from the thread, we have to exclude`maven-aether-provider` in order to get pack to work properly.

Would you consider publishing a non-uberjar version (possibly under different maven coordinates)?

**Comment by metasoarous** [comment]
Hi @stathissideris.

Thanks for reporting this! And sorry for not responding sooner; I've been swamped traveling for work.

I'm more than happy to start publishing Oz as a regular jar. Sorry that that the uberjar caused your team some hassle.

I've got some other work I've been wanting to release, and will try to do that by next week. I'll post back here when that's done.

Thanks again!

**Comment by rschmukler** [comment]
Hey @metasoarous just checking back on this. I also recently ran into an issue where the uberjar overwrote my version of aleph causing it to not be able to be required in my project.

**Comment by metasoarous** [comment]
@stathissideris @rschmukler Hi folks! Thanks again for reporting this. And sorry for the longer than expected wait!

I've just deployed `[metasoarous/oz "1.6.0-alpha6-SNAPSHOT"]`, which is _not_ built off an uberjar. I found I was able to load this in a project of mine in which I had been experiencing some dependency issues, which is a good sign. But please let me know if you're able to take it for a spin. I hope to have a non-SNAPSHOT release out in the next couple of days if everything looks good.

Thanks again!

**Comment by rschmukler** [comment]
Hey @metasoarous - just confirming that I tested `[metasoarous/oz "1.6.0-alpha6-SNAPSHOT"]` in my project and it worked great! Thanks!

**Comment by metasoarous** [comment]
Excellent! Thanks for the report @rschmukler. I'm going to go ahead and close this, but please let me know @stathissideris if you continue to have problems with the latest release.

Thanks!

PS @rschmukler: There's now a non-SNAPSHOT release out if you'd like to switch to that.
