### ISSUE TITLE
Idea: clojure-workbook

### ISSUE THREAD

**Issue by awb99** [metasoarous/oz#79]
I have a dream: I propose a merger of oz with gorillagrepl with added workbook sharing.

On a central site users could explore thousands of clojure workbooks written by other users. And then fork them and do little experiments on your own. 

It would be easy to see how libraries should be used, as for most libraries there would. be a demo workbook written by the library developer. 

Step by step plan:

1. Docker image of gorilla repl. Refactor all current gorilla view plugins so they actually work. 

2. Hack gorilla repl to load worksheets not from local file system but from github gists.
Thia means that users keep ownership of their source but can publish what they want. Hard code a few gist ids that are available, until we have 50 cool gists. 

3. Add github authentication to gorilla repl. Add a database of gist info (gist id, tags, description), of users (git id, favorites, stars). Add discuss messages to each gist.
Run on clojure-workbook.com.. Users can start adding and editing their workbooks.

4. Now most likely the will be many users. The one gigantic repl that powers all gists will not be enough. So run multiple repl engines, each gist that was running gets its own docker-repl engine. But 8 hours after it was started it will be stopped. Power users can run a repl on their machine and in the web config can chose to connect to the repl on their ip. 

5. Now we want more interactive features.. Like you have it in oz. So take the oz reagent server and merge the gorilla js code to it. Essentially the repl has to retransmit state to the reagent ap. So in the repl there need to be atom watchers that then update reagent atoms. 

Why not clojupter?  Jupyter has great ui.. But it is a lot of overhead. Since gorilla repl already has everything that is needed it only complicates things. 

I think this idea could catapult clojure to the top in data science and education. 

1+2+3 should not take more than a few days alltogether. And lots of coffee... 

To me this would round up figwheel and dev cards by a missing element. And for the first time ever will we have something like a js fiddle for clojure.. But intended to do data science.. not to test code. 

Let me know what you think...

**Comment by jefffriesen** [comment]
I would love to have a really good clojure or clojurescript notebook for lots of things, but especially data science. Jupyter notebooks are extremely useful, but they are clunky. For example, out of order computation, implicit state, and lack of 'run all, top to bottom' keybindings. And it's (mostly) Python, which has an amazing ecosystem but not my favorite language to write.

A few notes and questions:
1. Observable notebooks have solved some of these issues listed above. If you're shooting for a notebook experience, Observable is good benchmarks. They run Javascript code, but the underlying code is  built on an interpreter slightly different than Javascript: https://observablehq.com/@observablehq/observables-not-javascript

Two of the main devs are amazing (Mike Bostock and Jeremy Ashkenas). Here are some examples of observable notebooks:
https://observablehq.com/@observablehq/file-attachments
https://observablehq.com/@awoodruff/daylight-saving-time-gripe-assistant-tool

So one reason to bring up Observable is to look at an example of a nice implementation. Another is to explore whether it's a good idea to build on top of Observable notebooks (using clojurescript). Could that solve a lot of problems, or add more problems and constraints?

2. Another question that I wasn't sure about from your description: Would this be able to be run local-only, or would it have to be hosted online with gists? I personally think local-only would be important - the public notebooks would represent the tip of the iceberg. Jupyter is an essential tool right now and most of them are only run on your local machine.

3. IDE/Editor support: You talk about interacting through a repl, which is great. But how is the rest of the code written? I assume it's through an editor like emacs or cursive or vscode, but it's not clear with the comments about a gist. Would it have to be published to a gist first before interacting through the repl? 

Whatever you decide - I would love to see this feature. Congrats on cljtogether funding!

**Comment by awb99** [comment]
Hi @jefffriesen 

Thanks for the input on observable. It does have some cool features.

We already have a lot of the Jupyter features in a 100% pure clojure / clojurescript version:
https://github.com/pink-gorilla/gorilla-notebook

You can either clone and compile and run locally. Or you get the docker image from dockerhub
and you can run that locally.

We are very alpha at the moment. Saving only works with local files. 

Clojure Plugin system is working with add-dependency function that downloads and requires jars at runtime. We made a simple ui plugin system also (the interface of which most likely will change)

Clojurescript integration is not yet there, but should be there shortly.

Sample notebooks are here: https://github.com/pink-gorilla/sample-notebooks

If you need help - ticket on pinkgorilla notebook github or on zulip clourians chat #pinkgorilla

In regards to your question: we will offer a fully hosted version on pinkgorilla.org. And obvisously
in this scenario saving notebooks to a private cloud storage is important. So we want to offer
git gist cloud storage to begin with, and other to follow.

To me being able to easily share notebooks online is quite important. Also to have an explorer
where you can explore publicly shared notebooks - good to get ideas on what is possible, and what
other people did.

**Comment by jefffriesen** [comment]
Thanks @awb99 - looking forward to seeing how this evolves.
