### ISSUE TITLE
build! breaks on windows due to regex incompatibility

### ISSUE THREAD

**Issue by cjbarre** [metasoarous/oz#81]
On windows, two forward slashes are returned by java.io.File/separator, which breaks the re-pattern function. 

The solution appears to be to replace this sequence with four forward slashes (double escape).

I have a PR here, it's minimal and I can handle any re-arrangement of it if it's not quite to your liking.

https://github.com/metasoarous/oz/pull/80

--

I'm not sure if this is related, but on windows, the file being worked in does not automatically render in the web application in live view mode, I have to navigate to the path myself.

**Comment by metasoarous** [comment]
Hi @cjbarre! Thanks for the report and PR! I'll take a look and try to get merged soon.

Thanks again!

**Comment by cjbarre** [comment]
Thanks for the quick response @metasoarous, I'll also attempt to look into why the pages aren't rendering automatically.
