### ISSUE TITLE
Overriding default style

### ISSUE THREAD

**Issue by kennyjwilli** [metasoarous/oz#82]
What's the best way to override the default styling Oz provides? I'd like to use [Bulma](https://bulma.io/) to style my document and some of Oz's default styling clashes with Bulma.

**Comment by BorisVSchmid** [comment]
Same, question, but for tufte-css. Haven't really figured how to do that. Had it working at some point referring to an external stylesheet, but I couldn't figure out how to refer to the local stylesheet, nor could I get that assest copied over automatically.

**Comment by metasoarous** [comment]
Great question @kennyjwilli & @BorisVSchmid. Thanks for asking!

This isn't currently supported, but I'd like to add support for it. I'm thinking the right way to go is to add an option like `:extra-headers` to the relevant functions which lets you put whatever content you want/need in the header. Does that seem reasonable?

Thanks again!

**Comment by kennyjwilli** [comment]
@metasoarous Thanks for this library! It's been very useful to us. Which functions would accept `:extra-headers`? Is this something you'd do at build time or while actually using Oz?

**Comment by metasoarous** [comment]
@kennyjwilli Very glad to hear it :-)

My initial thought is that this would mostly be useful for the functions which build out to static content. Of course, it would be nice if the live view (when building out static content) matched.

Would you want this for the REPL functionality (`view!`) as well? I'm less inclined to support this, but would consider it if folks would find it useful.

Thanks!

**Comment by kennyjwilli** [comment]
I don't think so. I'm after the live view matching when building the content.

**Comment by BorisVSchmid** [comment]
Not using the (view! ) function yet, so it would work for me if I could alter what is in <head></head>. Right now I found that while I cannot remove an existing header, I can add a stylesheet in the site template. That works for me.

```
(defn site-template
  [spec]
  [:article
  [:link {:href #_"css/tufte.css" "https://edwardtufte.github.io/tufte-css/tufte.css"
          :rel "stylesheet"
          :type "text/css"}]
       spec])
```

**Comment by kennyjwilli** [comment]
Removing the css predefined in `head` is definitely important for us. It conflicts with styles we'd like to bring in.

**Comment by metasoarous** [comment]
Thank you both; Great feedback to have!

Sounds like we need an `:omit-oz-styles?` option, in addition to `:extra-headers`, the latter of which I think still makes sense for things like setting document titles and favicons. I'll add other `:omit-*` options as needed for other things which one should have the choice of leaving out (like LaTeX).

Please let me know if you think of anything else that needs additional customization along these lines.

Thanks again!

**Comment by kennyjwilli** [comment]
That sounds great! I like the ability to control things like LaTex. In our particular use case, we want everything besides the default Oz styles. 

Would `:omit-oz-styles?` be added to the `view!` function?

**Comment by wongjoel** [comment]
Wanted to add another vote for some mechanism like `omit-oz-styles?` and `:extra-headers` in at least the `export!` and `build!` functions.

Also wanted to note a hacky workaround in the meantime is to add javascript to add/remove stylesheets and change title/favicon (In case anyone reading this is like me in not initially realising that you can do it from javascript as a last resort).

**Comment by metasoarous** [comment]
Thanks again for all your thoughts on this issue folks, and for your patience. This has been at least partially implemented for a few releases, but I've failed to get around to updating the issue. The latest release (`1.6.0-alpha31` as of this writing) features options:

* `:omit-shortcut-icon?` (or `:shortcut-icon` if you'd like to supply your own)
* `:omit-styles?`
* `:omit-vega-libs?`
* `:header-extras` which let's you put in whatever additional header hiccup content you like

Closing for now, but please let me know if you have any other questions/comments in relation to this.

Thanks!
