### ISSUE TITLE
Cannot click on links when building a local website

### ISSUE THREAD

**Issue by BorisVSchmid** [metasoarous/oz#83]
When I click on local links in a website I am building (using oz/build!), Oz takes me to its waiting-for-plot screen, rather than to the local link.

```Waiting for first spec to load...
This may take a second the first time if you call a plot function, unless you first call start-server!.

**Comment by BorisVSchmid** [comment]
had some error in my local links. works now.

**Comment by metasoarous** [comment]
@BorisVSchmid Glad you got it sorted out! :+1:
