### ISSUE TITLE
404 on vega-embed@4.4.0 for exported visualization

### ISSUE THREAD

**Issue by sparkofreason** [metasoarous/oz#89]
Using version 1.6.0-alpha5. Loading the exported HTML gives a 404 on https://cdn.jsdelivr.net/npm/vega-embed@4.4.0, and subsequent related errors, charts do not render. If I manually edit the file and change to vega-embed@4.0.0, it works.

**Comment by metasoarous** [comment]
Thanks for the report @sparkofreason! I'm cutting a release in the next couple days (if everything goes as planned), and will fix this.

Thanks!

**Comment by metasoarous** [comment]
Hi @sparkofreason. This should now be fixed in the latest release (`1.6.0-alpha6`). Please give it a shot and reopen if if you're still having troubles.

Thanks again!
