### ISSUE TITLE
unnecessary requires in cljs/oz.core?

### ISSUE THREAD

**Issue by judepayne** [metasoarous/oz#99]
Hi,
I was trying to get the clojurescript functionality working, under shadow cljs.
shadow had a problem with (I think most of/ all of) these requires in cljs/oz.core

            [cljs.core.async :as async  :refer (<! >! put! chan)]
            [taoensso.encore :as encore :refer-macros (have have?)]
            [taoensso.timbre :as log :refer-macros (tracef debugf infof warnf errorf)]
            [taoensso.sente :as sente :refer (cb-success?)]
            [taoensso.sente.packers.transit :as sente-transit]

various macro expansion errors which I didn't note at the time apart from to see where they came from.
they didn't seem to be used at all in the core ns, so I removed them in my fork and no problems after that in shadow. perhaps remove them?

**Comment by metasoarous** [comment]
Hi @judepayne; Good catch. Thanks for letting me know!

The `oz.core` namespace used to house the machinery for live-view, which needs to listen on a sente channel for messages. But that was moved out into a separate namespace. So yes, these are no longer necessary and can be removed from the requires.

Would you please do a PR from your fork?

**Comment by judepayne** [comment]
Hi, that's done.

There's one other gotcha that I feel is worth a note in the cljs section of your README.

When in the vega spec supplied into the vega-lite function the value of the :data key is nil, then an Error will be thrown which in the console is something like can't call .url on undefined. This error will prevent the chart from being rendered in some browsers (e.g. Chrome on Windows, but not on a Mac).
My scenario was that my data was being fetched and put into an reagent atom whose initial value was nil, then the chart wouldn't be rendered even when vega-lite was called a second time once the atom was populated. Changing the default value of the atom to '() fixed it. It's a subtle error and probably worth a short note. I'll raise a separate PR for a short addition to the readme.

**Comment by metasoarous** [comment]
Great; Thank you! All merged in now.
